"""add opening_hours to pharmacies

Revision ID: 08d37bdc9d50
Revises: 39534c107876
Create Date: 2025-12-26 23:23:11.068152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08d37bdc9d50'
down_revision: Union[str, Sequence[str], None] = '39534c107876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('from_pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('to_pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('transfer_number', sa.String(length=50), nullable=False),
    sa.Column('transfer_type', sa.Enum('INTERNAL', 'EXTERNAL', name='transfertype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='transferstatus'), nullable=True),
    sa.Column('requested_date', sa.DateTime(), nullable=True),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('received_by_id', sa.UUID(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['to_pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_transfers_created_at'), 'product_transfers', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_transfers_tenant_id'), 'product_transfers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_product_transfers_transfer_number'), 'product_transfers', ['transfer_number'], unique=True)
    op.create_table('product_stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('quantity_lost', sa.Integer(), nullable=False),
    sa.Column('quantity_damaged', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('shelf', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='available, reserved, sold, expired, damaged, lost'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_stocks_batch_expiry', 'product_stocks', ['batch_number', 'expiry_date'], unique=False)
    op.create_index(op.f('ix_product_stocks_batch_number'), 'product_stocks', ['batch_number'], unique=False)
    op.create_index(op.f('ix_product_stocks_created_at'), 'product_stocks', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_stocks_expiry_date'), 'product_stocks', ['expiry_date'], unique=False)
    op.create_index('ix_product_stocks_expiry_status', 'product_stocks', ['expiry_date', 'status'], unique=False)
    op.create_index(op.f('ix_product_stocks_is_active'), 'product_stocks', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_stocks_product_id'), 'product_stocks', ['product_id'], unique=False)
    op.create_index('ix_product_stocks_product_status', 'product_stocks', ['product_id', 'status'], unique=False)
    op.create_index('ix_product_stocks_tenant_active', 'product_stocks', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_product_stocks_tenant_id'), 'product_stocks', ['tenant_id'], unique=False)
    op.create_table('purchase_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending, processing, completed, failed, cancelled'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_payments_payment_date'), 'purchase_payments', ['payment_date'], unique=False)
    op.create_index('ix_purchase_payments_tenant_date', 'purchase_payments', ['tenant_id', 'payment_date'], unique=False)
    op.create_index('ix_purchase_payments_tenant_status', 'purchase_payments', ['tenant_id', 'status'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False, comment='Positif pour entrée, négatif pour sortie'),
    sa.Column('movement_type', sa.String(length=50), nullable=False, comment='purchase, sale, adjustment, return, damage, loss, transfer'),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True, comment='invoice, order, adjustment, etc.'),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    op.create_index('ix_stock_movements_product_date', 'stock_movements', ['product_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_index('ix_stock_movements_reference', 'stock_movements', ['reference_number'], unique=False)
    op.create_index(op.f('ix_stock_movements_reference_number'), 'stock_movements', ['reference_number'], unique=False)
    op.create_index('ix_stock_movements_tenant_date', 'stock_movements', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_tenant_id'), 'stock_movements', ['tenant_id'], unique=False)
    op.create_index('ix_stock_movements_type_date', 'stock_movements', ['movement_type', 'created_at'], unique=False)
    op.create_table('transfer_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('approved_quantity', sa.Integer(), nullable=True),
    sa.Column('transferred_quantity', sa.Integer(), nullable=True),
    sa.Column('received_quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='transferstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['product_transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_items_transfer_id'), 'transfer_items', ['transfer_id'], unique=False)
    op.drop_index(op.f('ix_payments_payment_code'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_table('payments')
    op.add_column('audit_logs', sa.Column('action_type', sa.String(length=50), nullable=False, comment='CREATE, READ, UPDATE, DELETE, LOGIN, LOGOUT, EXPORT, IMPORT, VALIDATE, CANCEL'))
    op.add_column('audit_logs', sa.Column('action_category', sa.String(length=50), nullable=False, comment='system, security, data, financial, inventory, sales, purchases, clients, users'))
    op.add_column('audit_logs', sa.Column('entity_type', sa.String(length=100), nullable=False, comment='product, sale, purchase, client, user, inventory, stock_movement, payment, refund'))
    op.add_column('audit_logs', sa.Column('entity_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_name', sa.String(length=200), nullable=True))
    op.add_column('audit_logs', sa.Column('details', sa.JSON(), nullable=True, comment='Données détaillées au format JSON'))
    op.add_column('audit_logs', sa.Column('changes_before', sa.JSON(), nullable=True, comment='État avant modification'))
    op.add_column('audit_logs', sa.Column('changes_after', sa.JSON(), nullable=True, comment='État après modification'))
    op.add_column('audit_logs', sa.Column('changes_summary', sa.Text(), nullable=True, comment='Résumé des changements'))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('audit_logs', sa.Column('device_type', sa.String(length=50), nullable=True, comment='mobile, tablet, desktop, unknown'))
    op.add_column('audit_logs', sa.Column('browser', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('operating_system', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('latitude', sa.String(length=20), nullable=True))
    op.add_column('audit_logs', sa.Column('longitude', sa.String(length=20), nullable=True))
    op.add_column('audit_logs', sa.Column('duration_ms', sa.Integer(), nullable=True, comment="Durée de l'action en millisecondes"))
    op.add_column('audit_logs', sa.Column('status_code', sa.Integer(), nullable=True, comment='Code HTTP ou statut métier'))
    op.add_column('audit_logs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('stack_trace', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('reference_number', sa.String(length=100), nullable=True, comment='Numéro de référence (vente, achat, etc.)'))
    op.add_column('audit_logs', sa.Column('batch_id', sa.UUID(), nullable=True, comment='ID de lot pour les opérations groupées'))
    op.add_column('audit_logs', sa.Column('parent_log_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('severity', sa.String(length=20), nullable=False, comment='debug, info, warning, error, critical'))
    op.add_column('audit_logs', sa.Column('source_module', sa.String(length=100), nullable=True, comment='Module source (api, service, worker, etc.)'))
    op.add_column('audit_logs', sa.Column('request_id', sa.String(length=100), nullable=True, comment='ID de requête pour le tracing'))
    op.add_column('audit_logs', sa.Column('session_id', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('audit_logs', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(),
               comment='IPv4 ou IPv6',
               existing_nullable=True)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_audit_logs_action_category'), 'audit_logs', ['action_category'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index('ix_audit_logs_batch', 'audit_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_batch_id'), 'audit_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_date_hour', 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index('ix_audit_logs_reference', 'audit_logs', ['reference_number'], unique=False)
    op.create_index(op.f('ix_audit_logs_reference_number'), 'audit_logs', ['reference_number'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_severity'), 'audit_logs', ['severity'], unique=False)
    op.create_index('ix_audit_logs_tenant_action_date', 'audit_logs', ['tenant_id', 'action_type', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_tenant_date_range', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_tenant_entity', 'audit_logs', ['tenant_id', 'entity_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_logs_tenant_ip', 'audit_logs', ['tenant_id', 'ip_address', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_tenant_severity', 'audit_logs', ['tenant_id', 'severity', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_tenant_user_date', 'audit_logs', ['tenant_id', 'user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint(op.f('audit_logs_tenant_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'audit_logs', ['parent_log_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'action')
    op.drop_column('audit_logs', 'cible')
    op.add_column('pharmacies', sa.Column('opening_hours', sa.JSON(), nullable=True))
    op.alter_column('pharmacies', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    #op.alter_column('pharmacies', 'license_number',
    #          existing_type=sa.VARCHAR(length=100),
    #          nullable=False)
    op.alter_column('pharmacies', 'pharmacy_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('pharmacies', 'address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('pharmacies', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('pharmacies', 'country',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               nullable=False)
    op.alter_column('pharmacies', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pharmacies', 'is_main',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Pharmacie principale du tenant',
               existing_nullable=True)
    op.alter_column('pharmacies', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('pharmacies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pharmacies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_pharmacies_is_active'), table_name='pharmacies')
    op.drop_index(op.f('idx_pharmacies_is_main'), table_name='pharmacies')
    op.drop_index(op.f('idx_pharmacies_pharmacy_code'), table_name='pharmacies')
    op.drop_index(op.f('idx_pharmacies_tenant_id'), table_name='pharmacies')
    op.drop_index(op.f('unique_main_pharmacy_per_tenant'), table_name='pharmacies', postgresql_where='(is_main = true)')
    op.create_index(op.f('ix_pharmacies_id'), 'pharmacies', ['id'], unique=False)
    op.create_unique_constraint(None, 'pharmacies', ['license_number'])
    op.add_column('products', sa.Column('pharmacy_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_products_pharmacy_id'), 'products', ['pharmacy_id'], unique=False)
    op.create_foreign_key(None, 'products', 'pharmacies', ['pharmacy_id'], ['id'])
    op.alter_column('purchase_items', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, ordered, partial, received, cancelled',
               existing_nullable=False)
    op.create_index('ix_purchase_items_batch', 'purchase_items', ['tenant_id', 'batch_number'], unique=False)
    op.create_index('ix_purchase_items_product', 'purchase_items', ['tenant_id', 'product_id'], unique=False)
    op.create_index('ix_purchase_items_purchase', 'purchase_items', ['tenant_id', 'purchase_id'], unique=False)
    op.create_index(op.f('ix_purchases_created_at'), 'purchases', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchases_invoice_number'), 'purchases', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_purchases_purchase_date'), 'purchases', ['purchase_date'], unique=False)
    op.create_index('ix_purchases_tenant_supplier', 'purchases', ['tenant_id', 'supplier_id'], unique=False)
    op.add_column('sale_items', sa.Column('pharmacy_id', sa.UUID(), nullable=False))
    op.create_index('ix_sale_items_pharmacy', 'sale_items', ['pharmacy_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_pharmacy_id'), 'sale_items', ['pharmacy_id'], unique=False)
    op.create_foreign_key(None, 'sale_items', 'pharmacies', ['pharmacy_id'], ['id'])
    op.add_column('sales', sa.Column('pharmacy_id', sa.UUID(), nullable=False))
    op.create_index('ix_sales_pharmacy', 'sales', ['pharmacy_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sales_pharmacy_id'), 'sales', ['pharmacy_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'pharmacies', ['pharmacy_id'], ['id'])
    op.alter_column('tenants', 'adresse',
               existing_type=sa.VARCHAR(length=500),
               comment='Adresse complète de la pharmacie',
               existing_nullable=True)
    op.alter_column('tenants', 'max_pharmacies',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    #op.alter_column('user_pharmacy', 'id',
    #           existing_type=sa.UUID(),
    #          type_=sa.Integer(),
    #           existing_nullable=False,
    #          autoincrement=True,
    #          existing_server_default=sa.text('gen_random_uuid()'))
    #op.alter_column('user_pharmacy', 'pharmacy_id',
    #           existing_type=sa.UUID(),
    #           type_=sa.Integer(),
    #           existing_nullable=False)
    #op.alter_column('user_pharmacy', 'is_primary',
    #         existing_type=sa.BOOLEAN(),
    #          server_default=None,
    #          existing_nullable=True)
    op.alter_column('user_pharmacy', 'role_in_pharmacy',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_pharmacy', 'can_manage',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_pharmacy', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_user_pharmacy_is_primary'), table_name='user_pharmacy')
    op.drop_index(op.f('idx_user_pharmacy_pharmacy_id'), table_name='user_pharmacy')
    op.drop_index(op.f('idx_user_pharmacy_role'), table_name='user_pharmacy')
    op.drop_index(op.f('idx_user_pharmacy_user_id'), table_name='user_pharmacy')
    op.drop_index(op.f('unique_primary_pharmacy_per_user'), table_name='user_pharmacy', postgresql_where='(is_primary = true)')
    op.drop_index(op.f('unique_user_pharmacy'), table_name='user_pharmacy')
    op.create_index('idx_user_pharmacy_pharmacy', 'user_pharmacy', ['pharmacy_id'], unique=False)
    op.create_index('idx_user_pharmacy_user', 'user_pharmacy', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_pharmacy_id'), 'user_pharmacy', ['id'], unique=False)
    op.create_unique_constraint('uq_user_pharmacy', 'user_pharmacy', ['user_id', 'pharmacy_id'])
    op.alter_column('users', 'sms_verify_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sms_verify_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.drop_constraint('uq_user_pharmacy', 'user_pharmacy', type_='unique')
    op.drop_index(op.f('ix_user_pharmacy_id'), table_name='user_pharmacy')
    op.drop_index('idx_user_pharmacy_user', table_name='user_pharmacy')
    op.drop_index('idx_user_pharmacy_pharmacy', table_name='user_pharmacy')
    op.create_index(op.f('unique_user_pharmacy'), 'user_pharmacy', ['user_id', 'pharmacy_id'], unique=True)
    op.create_index(op.f('unique_primary_pharmacy_per_user'), 'user_pharmacy', ['user_id'], unique=True, postgresql_where='(is_primary = true)')
    op.create_index(op.f('idx_user_pharmacy_user_id'), 'user_pharmacy', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_pharmacy_role'), 'user_pharmacy', ['role_in_pharmacy'], unique=False)
    op.create_index(op.f('idx_user_pharmacy_pharmacy_id'), 'user_pharmacy', ['pharmacy_id'], unique=False)
    op.create_index(op.f('idx_user_pharmacy_is_primary'), 'user_pharmacy', ['is_primary'], unique=False)
    op.alter_column('user_pharmacy', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_pharmacy', 'can_manage',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user_pharmacy', 'role_in_pharmacy',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'user'::character varying"),
               existing_nullable=True)
    op.alter_column('user_pharmacy', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user_pharmacy', 'pharmacy_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_pharmacy', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('tenants', 'max_pharmacies',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('tenants', 'adresse',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Adresse complète de la pharmacie',
               existing_nullable=True)
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_pharmacy_id'), table_name='sales')
    op.drop_index('ix_sales_pharmacy', table_name='sales')
    op.drop_column('sales', 'pharmacy_id')
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_index(op.f('ix_sale_items_pharmacy_id'), table_name='sale_items')
    op.drop_index('ix_sale_items_pharmacy', table_name='sale_items')
    op.drop_column('sale_items', 'pharmacy_id')
    op.drop_index('ix_purchases_tenant_supplier', table_name='purchases')
    op.drop_index(op.f('ix_purchases_purchase_date'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_invoice_number'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_created_at'), table_name='purchases')
    op.drop_index('ix_purchase_items_purchase', table_name='purchase_items')
    op.drop_index('ix_purchase_items_product', table_name='purchase_items')
    op.drop_index('ix_purchase_items_batch', table_name='purchase_items')
    op.alter_column('purchase_items', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pending, ordered, partial, received, cancelled',
               existing_nullable=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_pharmacy_id'), table_name='products')
    op.drop_column('products', 'pharmacy_id')
    op.drop_constraint(None, 'pharmacies', type_='unique')
    op.drop_index(op.f('ix_pharmacies_id'), table_name='pharmacies')
    op.create_index(op.f('unique_main_pharmacy_per_tenant'), 'pharmacies', ['tenant_id'], unique=True, postgresql_where='(is_main = true)')
    op.create_index(op.f('idx_pharmacies_tenant_id'), 'pharmacies', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_pharmacies_pharmacy_code'), 'pharmacies', ['pharmacy_code'], unique=False)
    op.create_index(op.f('idx_pharmacies_is_main'), 'pharmacies', ['is_main'], unique=False)
    op.create_index(op.f('idx_pharmacies_is_active'), 'pharmacies', ['is_active'], unique=False)
    op.alter_column('pharmacies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('pharmacies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('pharmacies', 'config',
               existing_type=sa.JSON(),
               server_default=sa.text('\'{"currency": "XOF", "language": "fr", "tax_rate": 18.0, "date_format": "dd/MM/yyyy", "enable_barcode": true, "decimal_precision": 2, "low_stock_threshold": 10, "enable_expiry_alerts": true, "require_prescription": true}\'::jsonb'),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('pharmacies', 'is_main',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Pharmacie principale du tenant',
               existing_nullable=True)
    op.alter_column('pharmacies', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('pharmacies', 'country',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'RDC'::character varying"),
               nullable=True)
    op.alter_column('pharmacies', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('pharmacies', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('pharmacies', 'pharmacy_code',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('pharmacies', 'license_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('pharmacies', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_column('pharmacies', 'opening_hours')
    op.add_column('audit_logs', sa.Column('cible', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('audit_logs_tenant_id_fkey'), 'audit_logs', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_user_date', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_severity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_ip', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_date_range', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_action_date', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_severity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_reference_number'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_reference', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_date_hour', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_batch_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_batch', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_category'), table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='IPv4 ou IPv6',
               existing_nullable=True)
    op.alter_column('audit_logs', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('audit_logs', 'updated_at')
    op.drop_column('audit_logs', 'session_id')
    op.drop_column('audit_logs', 'request_id')
    op.drop_column('audit_logs', 'source_module')
    op.drop_column('audit_logs', 'severity')
    op.drop_column('audit_logs', 'parent_log_id')
    op.drop_column('audit_logs', 'batch_id')
    op.drop_column('audit_logs', 'reference_number')
    op.drop_column('audit_logs', 'stack_trace')
    op.drop_column('audit_logs', 'error_message')
    op.drop_column('audit_logs', 'status_code')
    op.drop_column('audit_logs', 'duration_ms')
    op.drop_column('audit_logs', 'longitude')
    op.drop_column('audit_logs', 'latitude')
    op.drop_column('audit_logs', 'city')
    op.drop_column('audit_logs', 'region')
    op.drop_column('audit_logs', 'country')
    op.drop_column('audit_logs', 'operating_system')
    op.drop_column('audit_logs', 'browser')
    op.drop_column('audit_logs', 'device_type')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'changes_summary')
    op.drop_column('audit_logs', 'changes_after')
    op.drop_column('audit_logs', 'changes_before')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'entity_name')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    op.drop_column('audit_logs', 'action_category')
    op.drop_column('audit_logs', 'action_type')
    op.create_table('payments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payment_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='paymentstatus'), autoincrement=False, nullable=False),
    sa.Column('payment_method', postgresql.ENUM('CASH', 'MOBILE_MONEY', 'BANK_TRANSFER', 'CARD', 'OTHER', name='paymentmethod'), autoincrement=False, nullable=False),
    sa.Column('payment_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('payments_subscription_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey'))
    )
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_code'), 'payments', ['payment_code'], unique=True)
    op.drop_index(op.f('ix_transfer_items_transfer_id'), table_name='transfer_items')
    op.drop_table('transfer_items')
    op.drop_index('ix_stock_movements_type_date', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_tenant_id'), table_name='stock_movements')
    op.drop_index('ix_stock_movements_tenant_date', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_reference_number'), table_name='stock_movements')
    op.drop_index('ix_stock_movements_reference', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index('ix_stock_movements_product_date', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_type'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('ix_purchase_payments_tenant_status', table_name='purchase_payments')
    op.drop_index('ix_purchase_payments_tenant_date', table_name='purchase_payments')
    op.drop_index(op.f('ix_purchase_payments_payment_date'), table_name='purchase_payments')
    op.drop_table('purchase_payments')
    op.drop_index(op.f('ix_product_stocks_tenant_id'), table_name='product_stocks')
    op.drop_index('ix_product_stocks_tenant_active', table_name='product_stocks')
    op.drop_index('ix_product_stocks_product_status', table_name='product_stocks')
    op.drop_index(op.f('ix_product_stocks_product_id'), table_name='product_stocks')
    op.drop_index(op.f('ix_product_stocks_is_active'), table_name='product_stocks')
    op.drop_index('ix_product_stocks_expiry_status', table_name='product_stocks')
    op.drop_index(op.f('ix_product_stocks_expiry_date'), table_name='product_stocks')
    op.drop_index(op.f('ix_product_stocks_created_at'), table_name='product_stocks')
    op.drop_index(op.f('ix_product_stocks_batch_number'), table_name='product_stocks')
    op.drop_index('ix_product_stocks_batch_expiry', table_name='product_stocks')
    op.drop_table('product_stocks')
    op.drop_index(op.f('ix_product_transfers_transfer_number'), table_name='product_transfers')
    op.drop_index(op.f('ix_product_transfers_tenant_id'), table_name='product_transfers')
    op.drop_index(op.f('ix_product_transfers_created_at'), table_name='product_transfers')
    op.drop_table('product_transfers')
    # ### end Alembic commands ###
