"""fix financial transaction relationships

Revision ID: 098322955ab7
Revises: edf65b17c217
Create Date: 2025-12-20 16:18:06.496644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098322955ab7'
down_revision: Union[str, Sequence[str], None] = 'edf65b17c217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_transactions', sa.Column('sale_id', sa.UUID(), nullable=True))
    op.add_column('financial_transactions', sa.Column('expense_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'financial_transactions', 'expenses', ['expense_id'], ['id'])
    op.create_foreign_key(None, 'financial_transactions', 'sales', ['sale_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financial_transactions', type_='foreignkey')
    op.drop_constraint(None, 'financial_transactions', type_='foreignkey')
    op.drop_column('financial_transactions', 'expense_id')
    op.drop_column('financial_transactions', 'sale_id')
    # ### end Alembic commands ###
