"""Initial user and tenant tables

Revision ID: 12138e01f7b9
Revises: bc2f731ce3ae
Create Date: 2025-12-20 17:48:06.362926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12138e01f7b9'
down_revision: Union[str, Sequence[str], None] = 'bc2f731ce3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'expense_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='salary, rent, utilities, supplies, marketing, maintenance, other',
               existing_nullable=False)
    op.alter_column('expenses', 'recurrence_interval',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='daily, weekly, monthly, yearly',
               existing_nullable=True)
    op.alter_column('financial_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='sale, purchase, expense, income, transfer, adjustment',
               existing_nullable=False)
    op.drop_index(op.f('ix_financial_transactions_tenant_date'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_type_category'), table_name='financial_transactions')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.create_index('ix_tenants_email', 'tenants', ['email'], unique=False)
    op.add_column('users', sa.Column('nom_complet', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('permissions', sa.JSON(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False,
               comment=None,
               existing_comment='admin, manager, cashier, pharmacist')
    op.drop_column('users', 'nom')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               comment='admin, manager, cashier, pharmacist')
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'nom_complet')
    op.drop_index('ix_tenants_email', table_name='tenants')
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    op.create_index(op.f('ix_financial_transactions_type_category'), 'financial_transactions', ['transaction_type', 'category'], unique=False)
    op.create_index(op.f('ix_financial_transactions_tenant_date'), 'financial_transactions', ['tenant_id', 'transaction_date'], unique=False)
    op.alter_column('financial_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=30),
               comment='sale, purchase, expense, income, transfer, adjustment',
               existing_nullable=False)
    op.alter_column('expenses', 'recurrence_interval',
               existing_type=sa.VARCHAR(length=30),
               comment='daily, weekly, monthly, yearly',
               existing_nullable=True)
    op.alter_column('expenses', 'expense_type',
               existing_type=sa.VARCHAR(length=50),
               comment='salary, rent, utilities, supplies, marketing, maintenance, other',
               existing_nullable=False)
    # ### end Alembic commands ###
