"""add stock and tenant

Revision ID: 20ea916ebed9
Revises: 3c45b7b99ce3
Create Date: 2026-03-17 16:39:04.041436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import json

# revision identifiers, used by Alembic.
revision: str = '20ea916ebed9'
down_revision: Union[str, Sequence[str], None] = '3c45b7b99ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_stocks', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('product_stocks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='available, reserved, sold, expired, damaged, lost, unavailable',
               existing_comment='available, reserved, sold, expired, damaged, lost')
    op.alter_column('product_stocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('product_stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('products', 'product_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_comment='medicament, parapharmacie, materiel, autre')
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('products', 'tva_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_comment='Taux TVA en %')
    op.alter_column('products', 'has_tva',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'margin_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'prescription_required',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    
    # Correction: Ajout de la clause USING pour la conversion TEXT -> JSONB
    op.execute("""
        ALTER TABLE products 
        ALTER COLUMN meta_data TYPE JSONB 
        USING meta_data::jsonb
    """)
    op.alter_column('products', 'meta_data',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_comment='Métadonnées JSON supplémentaires')
               
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'is_discounted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'stock_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_comment='normal, low_stock, out_of_stock, over_stock')
    op.alter_column('products', 'expiry_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_comment='ok, warning, critical, expired, unknown')
    op.alter_column('products', 'total_sold',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'total_purchased',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('ix_products_tenant_barcode', 'products', ['tenant_id', 'barcode'], unique=False)
    op.create_index('ix_products_tenant_code_unique_soft', 'products', ['tenant_id', 'code'], unique=False)
    op.create_index('ix_products_tenant_name', 'products', ['tenant_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_tenant_name', table_name='products')
    op.drop_index('ix_products_tenant_code_unique_soft', table_name='products')
    op.drop_index('ix_products_tenant_barcode', table_name='products')
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('products', 'total_purchased',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'total_sold',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'expiry_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='ok, warning, critical, expired, unknown')
    op.alter_column('products', 'stock_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_comment='normal, low_stock, out_of_stock, over_stock')
    op.alter_column('products', 'is_discounted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'is_available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    
    # Correction pour le downgrade: reconvertir JSONB en TEXT
    op.alter_column('products', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=True,
               existing_comment='Métadonnées JSON supplémentaires')
    
    op.alter_column('products', 'prescription_required',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'margin_rate',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'has_tva',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'tva_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_comment='Taux TVA en %')
    op.alter_column('products', 'unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('products', 'product_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_comment='medicament, parapharmacie, materiel, autre')
    op.alter_column('product_stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product_stocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product_stocks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment='available, reserved, sold, expired, damaged, lost',
               existing_comment='available, reserved, sold, expired, damaged, lost, unavailable')
    op.alter_column('product_stocks', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###