"""add_invoice_and_invoice_payment_models

Revision ID: 2a0fd4438d55
Revises: d81907c50a78
Create Date: 2026-01-06 09:51:56.773539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a0fd4438d55'
down_revision: Union[str, Sequence[str], None] = 'd81907c50a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False, comment='cash, mobile_money, visa, bank_transfer, cheque, credit_note'),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('payment_meta', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mobile_operator', sa.String(length=20), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audit_logs', sa.Column('action', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('action_level', sa.String(length=20), nullable=True))
    op.alter_column('audit_logs', 'action_type',
               existing_type=sa.VARCHAR(length=50),
               comment='CREATE, READ, UPDATE, DELETE, LOGIN, LOGOUT, EXPORT, IMPORT, VALIDATE, CANCEL, OTHER',
               existing_comment='CREATE, READ, UPDATE, DELETE, LOGIN, LOGOUT, EXPORT, IMPORT, VALIDATE, CANCEL',
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='product, sale, purchase, client, user, inventory, stock_movement, payment, refund')
    op.alter_column('audit_logs', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Données détaillées au format JSON',
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='IPv4 ou IPv6',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_tenant_action_date'), table_name='audit_logs')
    op.create_index('ix_audit_logs_tenant_action_date', 'audit_logs', ['tenant_id', 'action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_level'), 'audit_logs', ['action_level'], unique=False)
    op.create_index('ix_audit_logs_tenant_action_type_date', 'audit_logs', ['tenant_id', 'action_type', 'created_at'], unique=False)
    op.add_column('invoice_items', sa.Column('item_type', sa.String(length=20), nullable=True, comment='product, service, subscription, discount, tax, shipping'))
    op.add_column('invoice_items', sa.Column('unit_of_measure', sa.String(length=20), nullable=True, comment='unit, box, pack, kg, liter, etc.'))
    op.add_column('invoice_items', sa.Column('discount_amount', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('invoice_items', sa.Column('affects_stock', sa.Boolean(), nullable=True))
    op.add_column('invoice_items', sa.Column('stock_adjustment_id', sa.UUID(), nullable=True))
    op.add_column('invoice_items', sa.Column('item_meta', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('invoice_payments', sa.Column('payment_id', sa.UUID(), nullable=True))
    op.add_column('invoice_payments', sa.Column('payment_gateway', sa.String(length=50), nullable=True))
    op.add_column('invoice_payments', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    op.add_column('invoice_payments', sa.Column('status', sa.String(length=20), nullable=True, comment='success, failed, pending, refunded, cancelled'))
    op.add_column('invoice_payments', sa.Column('payment_meta', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('invoice_payments', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('invoice_payments', sa.Column('bank_account', sa.String(length=50), nullable=True))
    op.add_column('invoice_payments', sa.Column('cheque_number', sa.String(length=50), nullable=True))
    op.add_column('invoice_payments', sa.Column('mobile_operator', sa.String(length=20), nullable=True, comment='airtel, orange, vodacom, mpesa'))
    op.add_column('invoice_payments', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    op.add_column('invoice_payments', sa.Column('card_last4', sa.String(length=4), nullable=True))
    op.add_column('invoice_payments', sa.Column('card_brand', sa.String(length=20), nullable=True))
    op.add_column('invoice_payments', sa.Column('subscription_id', sa.UUID(), nullable=True))
    op.add_column('invoice_payments', sa.Column('subscription_period', sa.String(length=20), nullable=True, comment='monthly, quarterly, yearly'))
    op.add_column('invoice_payments', sa.Column('payment_date', sa.DateTime(), nullable=True))
    op.add_column('invoice_payments', sa.Column('received_at', sa.DateTime(), nullable=True))
    op.add_column('invoice_payments', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('invoice_payments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('invoice_payments', 'payment_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               comment='cash, mobile_money, visa, mastercard, bank_transfer, cheque, credit_note',
               existing_nullable=False)
    op.add_column('invoices', sa.Column('invoice_prefix', sa.String(length=10), nullable=True))
    op.add_column('invoices', sa.Column('invoice_year', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('invoice_sequence', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('invoice_type', sa.String(length=20), nullable=True, comment='sale, subscription, proforma, credit_note'))
    op.add_column('invoices', sa.Column('currency', sa.String(length=3), nullable=True, comment='Devise: CDF, USD, EUR'))
    op.add_column('invoices', sa.Column('client_email', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('client_phone', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('subscription_plan', sa.String(length=50), nullable=True, comment="Plan d'abonnement facturé"))
    op.add_column('invoices', sa.Column('subscription_period', sa.String(length=20), nullable=True, comment='monthly, yearly'))
    op.add_column('invoices', sa.Column('subscription_start', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('subscription_end', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('shipping_amount', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('tax_exempt', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('payment_methods', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Liste des méthodes de paiement acceptées'))
    op.add_column('invoices', sa.Column('payment_gateway', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('payment_gateway_id', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('payment_gateway_status', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('receipt_path', sa.String(length=500), nullable=True))
    op.add_column('invoices', sa.Column('email_sent', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('email_sent_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('email_recipients', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('invoices', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('recurring_interval', sa.String(length=20), nullable=True, comment='monthly, quarterly, yearly'))
    op.add_column('invoices', sa.Column('next_invoice_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('parent_invoice_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('is_credit_note', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('credit_note_for', sa.UUID(), nullable=True))
    op.alter_column('invoices', 'client_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='draft, issued, sent, partially_paid, paid, overdue, cancelled, refunded',
               existing_comment='draft, issued, sent, paid, overdue, cancelled',
               existing_nullable=True)
    op.alter_column('invoices', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, partially_paid, paid, overdue, failed, refunded',
               existing_comment='pending, partially_paid, paid, overdue',
               existing_nullable=True)
    op.create_foreign_key(None, 'invoices', 'invoices', ['parent_invoice_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'invoices', ['credit_note_for'], ['id'])
    op.drop_column('invoices', 'last_payment_date')
    
    # ============================================
    # CORRECTION: Remplir les valeurs NULL avant de rendre NOT NULL
    # ============================================
    
    # 1. D'abord, remplir les valeurs NULL dans license_number
    op.execute("""
        UPDATE pharmacies 
        SET license_number = 'PENDING-' || id::varchar 
        WHERE license_number IS NULL OR license_number = ''
    """)
    
    # 2. Maintenant, rendre la colonne NOT NULL
    op.alter_column('pharmacies', 'license_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    
    op.alter_column('user_pharmacy', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_pharmacy', 'pharmacy_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_pharmacy', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_user_pharmacy_id'), table_name='user_pharmacy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_pharmacy_id'), 'user_pharmacy', ['id'], unique=False)
    op.alter_column('user_pharmacy', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('user_pharmacy', 'pharmacy_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_pharmacy', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    
    # ============================================
    # CORRECTION: Dans le downgrade aussi
    # ============================================
    op.alter_column('pharmacies', 'license_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    
    # Optionnel: Remettre les valeurs 'PENDING-' à NULL si vous voulez
    # op.execute("""
    #     UPDATE pharmacies 
    #     SET license_number = NULL 
    #     WHERE license_number LIKE 'PENDING-%'
    # """)
    
    op.add_column('invoices', sa.Column('last_payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.alter_column('invoices', 'payment_status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending, partially_paid, paid, overdue',
               existing_comment='pending, partially_paid, paid, overdue, failed, refunded',
               existing_nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='draft, issued, sent, paid, overdue, cancelled',
               existing_comment='draft, issued, sent, partially_paid, paid, overdue, cancelled, refunded',
               existing_nullable=True)
    op.alter_column('invoices', 'client_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('invoices', 'credit_note_for')
    op.drop_column('invoices', 'is_credit_note')
    op.drop_column('invoices', 'parent_invoice_id')
    op.drop_column('invoices', 'next_invoice_date')
    op.drop_column('invoices', 'recurring_interval')
    op.drop_column('invoices', 'is_recurring')
    op.drop_column('invoices', 'archived_at')
    op.drop_column('invoices', 'cancelled_at')
    op.drop_column('invoices', 'email_recipients')
    op.drop_column('invoices', 'email_sent_at')
    op.drop_column('invoices', 'email_sent')
    op.drop_column('invoices', 'receipt_path')
    op.drop_column('invoices', 'payment_gateway_status')
    op.drop_column('invoices', 'payment_gateway_id')
    op.drop_column('invoices', 'payment_gateway')
    op.drop_column('invoices', 'payment_methods')
    op.drop_column('invoices', 'tax_exempt')
    op.drop_column('invoices', 'shipping_amount')
    op.drop_column('invoices', 'subscription_end')
    op.drop_column('invoices', 'subscription_start')
    op.drop_column('invoices', 'subscription_period')
    op.drop_column('invoices', 'subscription_plan')
    op.drop_column('invoices', 'client_phone')
    op.drop_column('invoices', 'client_email')
    op.drop_column('invoices', 'currency')
    op.drop_column('invoices', 'invoice_type')
    op.drop_column('invoices', 'invoice_sequence')
    op.drop_column('invoices', 'invoice_year')
    op.drop_column('invoices', 'invoice_prefix')
    op.alter_column('invoice_payments', 'payment_method',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='cash, mobile_money, visa, mastercard, bank_transfer, cheque, credit_note',
               existing_nullable=False)
    op.drop_column('invoice_payments', 'updated_at')
    op.drop_column('invoice_payments', 'confirmed_at')
    op.drop_column('invoice_payments', 'received_at')
    op.drop_column('invoice_payments', 'payment_date')
    op.drop_column('invoice_payments', 'subscription_period')
    op.drop_column('invoice_payments', 'subscription_id')
    op.drop_column('invoice_payments', 'card_brand')
    op.drop_column('invoice_payments', 'card_last4')
    op.drop_column('invoice_payments', 'mobile_number')
    op.drop_column('invoice_payments', 'mobile_operator')
    op.drop_column('invoice_payments', 'cheque_number')
    op.drop_column('invoice_payments', 'bank_account')
    op.drop_column('invoice_payments', 'bank_name')
    op.drop_column('invoice_payments', 'payment_meta')
    op.drop_column('invoice_payments', 'status')
    op.drop_column('invoice_payments', 'transaction_id')
    op.drop_column('invoice_payments', 'payment_gateway')
    op.drop_column('invoice_payments', 'payment_id')
    op.drop_column('invoice_items', 'item_meta')
    op.drop_column('invoice_items', 'stock_adjustment_id')
    op.drop_column('invoice_items', 'affects_stock')
    op.drop_column('invoice_items', 'discount_amount')
    op.drop_column('invoice_items', 'unit_of_measure')
    op.drop_column('invoice_items', 'item_type')
    op.drop_index('ix_audit_logs_tenant_action_type_date', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_level'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_action_date', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_tenant_action_date'), 'audit_logs', ['tenant_id', 'action_type', 'created_at'], unique=False)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(),
               comment='IPv4 ou IPv6',
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Données détaillées au format JSON',
               existing_nullable=True)
    op.alter_column('audit_logs', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_comment='product, sale, purchase, client, user, inventory, stock_movement, payment, refund')
    op.alter_column('audit_logs', 'action_type',
               existing_type=sa.VARCHAR(length=50),
               comment='CREATE, READ, UPDATE, DELETE, LOGIN, LOGOUT, EXPORT, IMPORT, VALIDATE, CANCEL',
               existing_comment='CREATE, READ, UPDATE, DELETE, LOGIN, LOGOUT, EXPORT, IMPORT, VALIDATE, CANCEL, OTHER',
               existing_nullable=False)
    op.drop_column('audit_logs', 'action_level')
    op.drop_column('audit_logs', 'action')
    op.drop_table('payments')
    # ### end Alembic commands ###