"""add_model_pharmacy_v2

Revision ID: 32511c8b91dc
Revises: becdc264e0d8
Create Date: 2026-03-18 00:18:25.502109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32511c8b91dc'
down_revision: Union[str, Sequence[str], None] = 'becdc264e0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacies', sa.Column('license_issuing_authority', sa.String(length=255), nullable=True))
    op.add_column('pharmacies', sa.Column('license_expiry_date', sa.DateTime(), nullable=True))
    op.add_column('pharmacies', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('pharmacies', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('pharmacies', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('pharmacies', sa.Column('pharmacy_type', sa.String(length=50), nullable=True, comment='retail, hospital, clinic'))
    op.add_column('pharmacies', sa.Column('pharmacist_contact', sa.String(length=50), nullable=True))
    op.add_column('pharmacies', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.drop_column('pharmacies', 'meta_data')
    op.drop_column('pharmacies', 'pharmacist_contact')
    op.drop_column('pharmacies', 'pharmacy_type')
    op.drop_column('pharmacies', 'longitude')
    op.drop_column('pharmacies', 'latitude')
    op.drop_column('pharmacies', 'website')
    op.drop_column('pharmacies', 'license_expiry_date')
    op.drop_column('pharmacies', 'license_issuing_authority')
   
    # ### end Alembic commands ###
