"""upgrade subscription pharma saas

Revision ID: 3a5b3b2aeaba
Revises: c373bc9bb648
Create Date: 2025-12-22 16:16:45.866482
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a5b3b2aeaba'
down_revision: Union[str, Sequence[str], None] = 'c373bc9bb648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'subscription_payments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('subscription_id', sa.UUID(), nullable=False),
        sa.Column('payment_code', sa.String(length=50), nullable=False),
        sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('amount_paid', sa.DECIMAL(precision=10, scale=2), nullable=False),

        sa.Column(
            'status',
            sa.Enum(
                'PENDING',
                'COMPLETED',
                'FAILED',
                'REFUNDED',
                'PARTIALLY_REFUNDED',
                name='paymentstatus',
                create_type=False
            ),
            nullable=False
        ),

        sa.Column(
            'payment_method',
            sa.Enum(
                'CASH',
                'MOBILE_MONEY',
                'BANK_TRANSFER',
                'CARD',
                'OTHER',
                name='paymentmethod',
                create_type=False
            ),
            nullable=False
        ),

        sa.Column('payment_reference', sa.String(length=100), nullable=True),
        sa.Column('period_start', sa.DateTime(), nullable=False),
        sa.Column('period_end', sa.DateTime(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('meta_data', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('paid_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_subscription_payments_payment_code'),
        'subscription_payments',
        ['payment_code'],
        unique=True
    )

    op.create_index(
        op.f('ix_subscription_payments_subscription_id'),
        'subscription_payments',
        ['subscription_id'],
        unique=False
    )

    op.drop_index(op.f('ix_payments_payment_code'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'payments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('subscription_id', sa.UUID(), nullable=False),
        sa.Column('payment_code', sa.String(length=50), nullable=False),
        sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column('amount_paid', sa.NUMERIC(precision=10, scale=2), nullable=False),

        sa.Column(
            'status',
            postgresql.ENUM(
                'PENDING',
                'COMPLETED',
                'FAILED',
                'REFUNDED',
                'PARTIALLY_REFUNDED',
                name='paymentstatus',
                create_type=False
            ),
            nullable=False
        ),

        sa.Column(
            'payment_method',
            postgresql.ENUM(
                'CASH',
                'MOBILE_MONEY',
                'BANK_TRANSFER',
                'CARD',
                'OTHER',
                name='paymentmethod',
                create_type=False
            ),
            nullable=False
        ),

        sa.Column('payment_reference', sa.String(length=100), nullable=True),
        sa.Column('period_start', sa.DateTime(), nullable=False),
        sa.Column('period_end', sa.DateTime(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('meta_data', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('paid_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_payments_subscription_id'),
        'payments',
        ['subscription_id'],
        unique=False
    )

    op.create_index(
        op.f('ix_payments_payment_code'),
        'payments',
        ['payment_code'],
        unique=True
    )

    op.drop_index(
        op.f('ix_subscription_payments_subscription_id'),
        table_name='subscription_payments'
    )

    op.drop_index(
        op.f('ix_subscription_payments_payment_code'),
        table_name='subscription_payments'
    )

    op.drop_table('subscription_payments')
    # ### end Alembic commands ###
