"""make tenant_id nullable for super_admin

Revision ID: 3c45b7b99ce3
Revises: cef3a6cd6ebd
Create Date: 2026-03-06 05:09:59.260744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = '3c45b7b99ce3'
down_revision: Union[str, Sequence[str], None] = 'cef3a6cd6ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # CORRECTION 1: inventory_alerts avec UUID pour les clés étrangères
    op.create_table('inventory_alerts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', UUID(as_uuid=True), nullable=False),  # CHANGÉ: Integer -> UUID
        sa.Column('product_id', UUID(as_uuid=True), nullable=False), # CHANGÉ: Integer -> UUID
        sa.Column('alert_type', sa.String(length=50), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('is_resolved', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_alerts_id'), 'inventory_alerts', ['id'], unique=False)
    
    # Table user_subscriptions (déjà en UUID, inchangée)
    op.create_table('user_subscriptions',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', UUID(as_uuid=True), nullable=False),
        sa.Column('tenant_id', UUID(as_uuid=True), nullable=False),
        sa.Column('plan_type', sa.String(length=50), nullable=False),
        sa.Column('plan_name', sa.String(length=100), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=True),
        sa.Column('trial_end_date', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('billing_cycle', sa.String(length=20), nullable=True),
        sa.Column('max_users', sa.Integer(), nullable=False),
        sa.Column('max_products', sa.Integer(), nullable=False),
        sa.Column('max_pharmacies', sa.Integer(), nullable=False),
        sa.Column('payment_id', UUID(as_uuid=True), nullable=True),
        sa.Column('auto_renew', sa.Boolean(), nullable=True),
        sa.Column('cancelled_at', sa.DateTime(), nullable=True),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_tenant_id'), 'user_subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=True)
    
    # CORRECTION 2: Vérifier si l'index existe avant de le créer
    # Connexion à la base pour exécuter une requête SQL directe
    conn = op.get_bind()
    
    # Vérifier si l'index existe déjà
    result = conn.execute(
        sa.text("SELECT 1 FROM pg_indexes WHERE indexname = 'ix_inventory_items_product'")
    ).fetchone()
    
    # Créer l'index seulement s'il n'existe pas
    if not result:
        op.create_index('ix_inventory_items_product', 'inventory_items', ['tenant_id', 'product_id'], unique=False)
        print("Index ix_inventory_items_product créé avec succès.")
    else:
        print("Index ix_inventory_items_product existe déjà, création ignorée.")
    
    # Gestion des index sur tenants
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=False)
    op.drop_index(op.f('ix_tenants_tenant_code'), table_name='tenants')
    op.create_index(op.f('ix_tenants_tenant_code'), 'tenants', ['tenant_code'], unique=True)
    
    # Votre modification principale : rendre tenant_id nullable
    op.alter_column('users', 'tenant_id',
               existing_type=UUID(as_uuid=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Annuler la modification sur users
    op.alter_column('users', 'tenant_id',
               existing_type=UUID(as_uuid=True),
               nullable=False)
    
    # Restaurer les index sur tenants
    op.drop_index(op.f('ix_tenants_tenant_code'), table_name='tenants')
    op.create_index(op.f('ix_tenants_tenant_code'), 'tenants', ['tenant_code'], unique=False)
    op.drop_index('ix_tenants_slug', table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    
    # Supprimer les index et tables créés
    # Vérifier si l'index existe avant de le supprimer
    conn = op.get_bind()
    result = conn.execute(
        sa.text("SELECT 1 FROM pg_indexes WHERE indexname = 'ix_inventory_items_product'")
    ).fetchone()
    
    if result:
        op.drop_index('ix_inventory_items_product', table_name='inventory_items')
    
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_tenant_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_inventory_alerts_id'), table_name='inventory_alerts')
    op.drop_table('inventory_alerts')
    # ### end Alembic commands ###