"""initial pharma saas schema

Revision ID: 5846ce45657f
Revises: 
Create Date: 2025-12-20 15:24:05.989007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5846ce45657f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom_pharmacie', sa.String(length=200), nullable=False),
    sa.Column('nom_entreprise', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('telephone_secondaire', sa.String(length=20), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('commune', sa.String(length=100), nullable=True),
    sa.Column('quartier', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=50), nullable=True),
    sa.Column('coordonnees_gps', sa.String(length=100), nullable=True, comment='Latitude,Longitude'),
    sa.Column('numero_agrement', sa.String(length=50), nullable=True),
    sa.Column('registre_commerce', sa.String(length=50), nullable=True),
    sa.Column('nom_proprietaire', sa.String(length=150), nullable=False),
    sa.Column('num_contribuable', sa.String(length=50), nullable=True, comment='Numéro de contribuable'),
    sa.Column('id_nat', sa.String(length=50), nullable=True, comment="Numéro d'identification nationale"),
    sa.Column('type_pharmacie', sa.String(length=30), nullable=True, comment='officine, hospitaliere, veterinaire, parapharmacie'),
    sa.Column('specialite', sa.String(length=100), nullable=True),
    sa.Column('heures_ouverture', sa.String(length=100), nullable=True),
    sa.Column('jours_ouverture', sa.String(length=100), nullable=True),
    sa.Column('superficie', sa.String(length=50), nullable=True),
    sa.Column('nombre_employes', sa.String(length=20), nullable=True),
    sa.Column('devise', sa.String(length=3), nullable=True),
    sa.Column('langue', sa.String(length=10), nullable=True),
    sa.Column('fuseau_horaire', sa.String(length=50), nullable=True),
    sa.Column('format_date', sa.String(length=20), nullable=True),
    sa.Column('format_heure', sa.String(length=20), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True, comment='essai, actif, suspendu, expire, resiliation'),
    sa.Column('plan_abonnement', sa.String(length=20), nullable=True),
    sa.Column('date_debut_abonnement', sa.DateTime(), nullable=True),
    sa.Column('date_fin_essai', sa.DateTime(), nullable=True),
    sa.Column('date_prochain_paiement', sa.DateTime(), nullable=True),
    sa.Column('montant_abonnement', sa.String(length=20), nullable=True),
    sa.Column('periode_facturation', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('couleur_principale', sa.String(length=20), nullable=True),
    sa.Column('site_web', sa.String(length=200), nullable=True),
    sa.Column('reseaux_sociaux', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.Column('domaine_personnalise', sa.String(length=150), nullable=True),
    sa.Column('ssl_actif', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.Column('date_activation', sa.DateTime(), nullable=True),
    sa.Column('date_desactivation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('domaine_personnalise'),
    sa.UniqueConstraint('numero_agrement')
    )
    op.create_index('ix_tenants_api_key', 'tenants', ['api_key'], unique=False)
    op.create_index('ix_tenants_date_creation', 'tenants', ['date_creation'], unique=False)
    op.create_index('ix_tenants_domaine', 'tenants', ['domaine_personnalise'], unique=False)
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    op.create_index('ix_tenants_nom_pharmacie', 'tenants', ['nom_pharmacie'], unique=False)
    op.create_index('ix_tenants_plan', 'tenants', ['plan_abonnement'], unique=False)
    op.create_index('ix_tenants_statut', 'tenants', ['statut'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('type_client', sa.String(length=20), nullable=True, comment='particulier, professionnel, assureur, etat'),
    sa.Column('entreprise', sa.String(length=100), nullable=True),
    sa.Column('num_contribuable', sa.String(length=50), nullable=True),
    sa.Column('rccm', sa.String(length=50), nullable=True),
    sa.Column('id_nat', sa.String(length=50), nullable=True),
    sa.Column('credit_limit', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('eligible_credit', sa.Boolean(), nullable=True),
    sa.Column('dette_actuelle', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('total_achats', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('nombre_achats', sa.Integer(), nullable=True),
    sa.Column('moyenne_achat', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('date_inscription', sa.DateTime(), nullable=True),
    sa.Column('dernier_achat', sa.DateTime(), nullable=True),
    sa.Column('date_dernier_paiement', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('blacklisted', sa.Boolean(), nullable=True),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clients_credit_status', 'clients', ['tenant_id', 'eligible_credit', 'blacklisted'], unique=False)
    op.create_index('ix_clients_last_purchase', 'clients', ['tenant_id', 'dernier_achat'], unique=False)
    op.create_index('ix_clients_tenant_email', 'clients', ['tenant_id', 'email'], unique=False)
    op.create_index('ix_clients_tenant_nom', 'clients', ['tenant_id', 'nom'], unique=False)
    op.create_index('ix_clients_tenant_phone', 'clients', ['tenant_id', 'telephone'], unique=False)
    op.create_index('ix_clients_type', 'clients', ['tenant_id', 'type_client'], unique=False)
    op.create_table('inventory_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False, comment='daily, weekly, monthly, quarterly, yearly, cycle'),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True, comment='0-6 (Lundi-Dimanche)'),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('month_of_year', sa.Integer(), nullable=True),
    sa.Column('cycle_count', sa.Integer(), nullable=True),
    sa.Column('current_cycle', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_executed', sa.DateTime(), nullable=True),
    sa.Column('next_schedule', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True, comment='Code interne'),
    sa.Column('barcode', sa.String(length=100), nullable=True, comment='Code-barres'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('commercial_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active_ingredient', sa.String(length=200), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('galenic_form', sa.String(length=100), nullable=True, comment='Comprimé, sirop, injectable, etc.'),
    sa.Column('laboratory', sa.String(length=200), nullable=True),
    sa.Column('dci', sa.String(length=200), nullable=True, comment='Dénomination Commune Internationale'),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('therapeutic_class', sa.String(length=200), nullable=True),
    sa.Column('product_type', sa.String(length=30), nullable=True, comment='medicament, parapharmacie, materiel, autre'),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('alert_threshold', sa.Integer(), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.Column('maximum_stock', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True, comment='Emplacement physique'),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wholesale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tva_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Taux TVA en %'),
    sa.Column('has_tva', sa.Boolean(), nullable=True),
    sa.Column('margin_amount', sa.Numeric(precision=12, scale=2), sa.Computed('selling_price - purchase_price', persisted=True), nullable=True),
    sa.Column('margin_rate', sa.Numeric(precision=5, scale=2), sa.Computed('((selling_price - purchase_price) / NULLIF(purchase_price, 0)) * 100', persisted=True), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('authorization_number', sa.String(length=100), nullable=True),
    sa.Column('packaging', sa.String(length=100), nullable=True),
    sa.Column('prescription_required', sa.Boolean(), nullable=True),
    sa.Column('regulatory_class', sa.String(length=50), nullable=True, comment='Classe réglementaire: A, B, C, etc.'),
    sa.Column('main_supplier', sa.String(length=200), nullable=True),
    sa.Column('supplier_code', sa.String(length=100), nullable=True),
    sa.Column('supplier_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('leaflet_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True, comment='Métadonnées JSON supplémentaires'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_discounted', sa.Boolean(), nullable=True),
    sa.Column('stock_status', sa.String(length=20), nullable=True, comment='normal, low_stock, out_of_stock, over_stock'),
    sa.Column('expiry_status', sa.String(length=20), nullable=True, comment='ok, warning, critical, expired, unknown'),
    sa.Column('total_sold', sa.Integer(), nullable=True),
    sa.Column('total_purchased', sa.Integer(), nullable=True),
    sa.Column('last_sale_date', sa.DateTime(), nullable=True),
    sa.Column('last_purchase_date', sa.DateTime(), nullable=True),
    sa.Column('last_adjustment_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index('ix_products_expiry_date', 'products', ['expiry_date'], unique=False)
    op.create_index('ix_products_expiry_status', 'products', ['expiry_status'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_is_available'), 'products', ['is_available'], unique=False)
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('ix_products_stock_status', 'products', ['stock_status'], unique=False)
    op.create_index('ix_products_tenant_active', 'products', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=True),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Code unique du fournisseur'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('type_supplier', sa.String(length=30), nullable=True, comment='company, individual, government'),
    sa.Column('tax_id', sa.String(length=50), nullable=True, comment='Numéro de contribuable'),
    sa.Column('rccm', sa.String(length=50), nullable=True, comment='Registre de commerce'),
    sa.Column('id_nat', sa.String(length=50), nullable=True, comment="Numéro d'identification nationale"),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('phone_secondary', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('bank_swift', sa.String(length=20), nullable=True),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Catégories de produits/services fournis'),
    sa.Column('specialities', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Spécialités'),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=2), nullable=True, comment='Note sur 5'),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('reliability_score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Score de fiabilité'),
    sa.Column('delivery_score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Score de livraison'),
    sa.Column('quality_score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Score de qualité'),
    sa.Column('total_transactions', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('average_delivery_time', sa.Integer(), nullable=True, comment='Temps de livraison moyen en jours'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='active, inactive, blacklisted, pending'),
    sa.Column('is_preferred', sa.Boolean(), nullable=True, comment='Fournisseur préféré'),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('supplier_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_order_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_code'), 'suppliers', ['code'], unique=True)
    op.create_index('ix_suppliers_tenant_code', 'suppliers', ['tenant_id', 'code'], unique=False)
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)
    op.create_index('ix_suppliers_tenant_name', 'suppliers', ['tenant_id', 'name'], unique=False)
    op.create_index('ix_suppliers_tenant_rating', 'suppliers', ['tenant_id', 'rating'], unique=False)
    op.create_index('ix_suppliers_tenant_status', 'suppliers', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_suppliers_tenant_type', 'suppliers', ['tenant_id', 'type_supplier'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True, comment='admin, manager, cashier, pharmacist'),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('cible', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('allocated_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('spent_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('committed_amount', sa.DECIMAL(precision=15, scale=2), nullable=True, comment='Montant engagé mais non encore payé'),
    sa.Column('remaining_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('warning_threshold', sa.DECIMAL(precision=5, scale=2), nullable=True, comment="Seuil d'avertissement en %"),
    sa.Column('critical_threshold', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Seuil critique en %'),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True, comment='active, closed, cancelled'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('budget_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('allocated_amount >= 0', name='check_budget_amount_positive'),
    sa.CheckConstraint('start_date <= end_date', name='check_budget_dates'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_code'), 'budgets', ['code'], unique=True)
    op.create_index('ix_budgets_tenant_category', 'budgets', ['tenant_id', 'category'], unique=False)
    op.create_index(op.f('ix_budgets_tenant_id'), 'budgets', ['tenant_id'], unique=False)
    op.create_index('ix_budgets_tenant_period', 'budgets', ['tenant_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_budgets_tenant_status', 'budgets', ['tenant_id', 'status'], unique=False)
    op.create_table('capitals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('capital_type', sa.String(length=30), nullable=False, comment='initial, additional, withdrawal, reinvestment'),
    sa.Column('capital_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True, comment='banque, caisse, investisseur'),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='pending, approved, completed, cancelled'),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False, comment='daily, weekly, monthly, quarterly, yearly'),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_name', sa.String(length=100), nullable=False),
    sa.Column('total_sales', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_cost', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('gross_profit', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('total_expenses', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('net_profit', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_financial_periods_period_range', 'financial_periods', ['period_start', 'period_end'], unique=False)
    op.create_index('ix_financial_periods_tenant_period', 'financial_periods', ['tenant_id', 'period_type', 'period_start'], unique=False)
    op.create_table('physical_inventories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('inventory_type', sa.String(length=20), nullable=False, comment='complete, partial, spot, cycle'),
    sa.Column('inventory_number', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='draft, in_progress, counting, validation, completed, cancelled'),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('counted_by', sa.UUID(), nullable=True),
    sa.Column('validated_by', sa.UUID(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('items_counted', sa.Integer(), nullable=True),
    sa.Column('items_missing', sa.Integer(), nullable=True),
    sa.Column('items_excess', sa.Integer(), nullable=True),
    sa.Column('system_value', sa.Float(), nullable=True),
    sa.Column('counted_value', sa.Float(), nullable=True),
    sa.Column('variance_value', sa.Float(), nullable=True),
    sa.Column('variance_percentage', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['counted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventories_tenant_date', 'physical_inventories', ['tenant_id', 'start_date'], unique=False)
    op.create_index('ix_inventories_tenant_status', 'physical_inventories', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_physical_inventories_inventory_number'), 'physical_inventories', ['inventory_number'], unique=True)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('client_phone', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('seller_name', sa.String(length=100), nullable=False),
    sa.Column('validated_by', sa.UUID(), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=False, comment='cash, mobile_money, card, check, bank_transfer, credit'),
    sa.Column('reference_payment', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft, pending, completed, cancelled, refunded'),
    sa.Column('is_credit', sa.Boolean(), nullable=True),
    sa.Column('credit_due_date', sa.Date(), nullable=True),
    sa.Column('guarantee_deposit', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('guarantor_name', sa.String(length=100), nullable=True),
    sa.Column('guarantor_phone', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_discount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_tva', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('global_discount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_path', sa.String(length=500), nullable=True),
    sa.Column('receipt_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sale_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_sales_created_at'), 'sales', ['created_at'], unique=False)
    op.create_index('ix_sales_created_by', 'sales', ['tenant_id', 'created_by'], unique=False)
    op.create_index(op.f('ix_sales_reference'), 'sales', ['reference'], unique=True)
    op.create_index('ix_sales_tenant_client', 'sales', ['tenant_id', 'client_id'], unique=False)
    op.create_index('ix_sales_tenant_created', 'sales', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_sales_tenant_credit', 'sales', ['tenant_id', 'is_credit'], unique=False)
    op.create_index('ix_sales_tenant_payment', 'sales', ['tenant_id', 'payment_method'], unique=False)
    op.create_index('ix_sales_tenant_status', 'sales', ['tenant_id', 'status'], unique=False)
    op.create_table('costs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False, comment='Référence unique de la dépense'),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurring_until', sa.Date(), nullable=True),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True, comment='Justification de la dépense'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Liste des pièces jointes'),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='draft, submitted, approved, rejected, paid'),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('budget_id', sa.UUID(), nullable=True),
    sa.Column('is_budgeted', sa.Boolean(), nullable=True),
    sa.Column('budget_variance', sa.DECIMAL(precision=15, scale=2), nullable=True, comment='Différence entre budget alloué et dépense réelle'),
    sa.Column('cost_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('amount >= 0', name='check_amount_positive'),
    sa.CheckConstraint('total_amount >= 0', name='check_total_amount_positive'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costs_reference'), 'costs', ['reference'], unique=True)
    op.create_index('ix_costs_tenant_budget', 'costs', ['tenant_id', 'budget_id'], unique=False)
    op.create_index('ix_costs_tenant_category', 'costs', ['tenant_id', 'category'], unique=False)
    op.create_index('ix_costs_tenant_created_by', 'costs', ['tenant_id', 'created_by'], unique=False)
    op.create_index('ix_costs_tenant_date', 'costs', ['tenant_id', 'payment_date'], unique=False)
    op.create_index(op.f('ix_costs_tenant_id'), 'costs', ['tenant_id'], unique=False)
    op.create_index('ix_costs_tenant_status', 'costs', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_costs_tenant_supplier', 'costs', ['tenant_id', 'supplier_id'], unique=False)
    op.create_table('debts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('initial_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('paid_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('remaining_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('interest_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='pending, partially_paid, paid, overdue, defaulted, cancelled'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_debts_tenant_client', 'debts', ['tenant_id', 'client_id'], unique=False)
    op.create_index('ix_debts_tenant_due_date', 'debts', ['tenant_id', 'due_date'], unique=False)
    op.create_index('ix_debts_tenant_sale', 'debts', ['tenant_id', 'sale_id'], unique=False)
    op.create_index('ix_debts_tenant_status', 'debts', ['tenant_id', 'status'], unique=False)
    op.create_table('financial_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False, comment='sale, purchase, expense, income, transfer, adjustment'),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_transactions_category'), 'financial_transactions', ['category'], unique=False)
    op.create_index('ix_financial_transactions_tenant_date', 'financial_transactions', ['tenant_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_date'), 'financial_transactions', ['transaction_date'], unique=False)
    op.create_index('ix_financial_transactions_type_category', 'financial_transactions', ['transaction_type', 'category'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('counted_quantity', sa.Integer(), nullable=True),
    sa.Column('variance', sa.Integer(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('counted_value', sa.Float(), nullable=True),
    sa.Column('variance_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='pending, counted, validated, adjusted'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('counted_at', sa.DateTime(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['physical_inventories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_items_inventory', 'inventory_items', ['inventory_id', 'status'], unique=False)
    op.create_index('ix_inventory_items_product', 'inventory_items', ['tenant_id', 'product_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('client_address', sa.Text(), nullable=True),
    sa.Column('client_tax_id', sa.String(length=50), nullable=True),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_tax', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_discount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('tax_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='draft, issued, sent, paid, overdue, cancelled'),
    sa.Column('payment_status', sa.String(length=20), nullable=True, comment='pending, partially_paid, paid, overdue'),
    sa.Column('amount_paid', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('footer', sa.Text(), nullable=True),
    sa.Column('invoice_meta', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('xml_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('refund_method', sa.String(length=20), nullable=False, comment='cash, mobile_money, bank_transfer, store_credit'),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('refund_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('refund_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='pending, approved, processed, completed, rejected'),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('requestor_name', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approver_name', sa.String(length=100), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('processor_name', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('sale_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('discount_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('tva_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('discount_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('tva_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_items_batch', 'sale_items', ['tenant_id', 'batch_number'], unique=False)
    op.create_index('ix_sale_items_product', 'sale_items', ['tenant_id', 'product_id'], unique=False)
    op.create_index('ix_sale_items_sale', 'sale_items', ['tenant_id', 'sale_id'], unique=False)
    op.create_table('debt_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('debt_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False, comment='cash, mobile_money, card, check, bank_transfer'),
    sa.Column('mobile_network', sa.String(length=20), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('card_last_four', sa.String(length=4), nullable=True),
    sa.Column('card_type', sa.String(length=20), nullable=True),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='success, failed, pending, refunded'),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('ix_debt_payments_client', 'debt_payments', ['tenant_id', 'client_id'], unique=False)
    op.create_index('ix_debt_payments_debt', 'debt_payments', ['tenant_id', 'debt_id'], unique=False)
    op.create_index('ix_debt_payments_processor', 'debt_payments', ['tenant_id', 'processed_by'], unique=False)
    op.create_index('ix_debt_payments_reference', 'debt_payments', ['reference'], unique=False)
    op.create_index('ix_debt_payments_sale', 'debt_payments', ['tenant_id', 'sale_id'], unique=False)
    op.create_index('ix_debt_payments_tenant_date', 'debt_payments', ['tenant_id', 'created_at'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('expense_type', sa.String(length=50), nullable=False, comment='salary, rent, utilities, supplies, marketing, maintenance, other'),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('payee', sa.String(length=200), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_interval', sa.String(length=30), nullable=True, comment='daily, weekly, monthly, yearly'),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('discount_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_payments')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_debt_payments_tenant_date', table_name='debt_payments')
    op.drop_index('ix_debt_payments_sale', table_name='debt_payments')
    op.drop_index('ix_debt_payments_reference', table_name='debt_payments')
    op.drop_index('ix_debt_payments_processor', table_name='debt_payments')
    op.drop_index('ix_debt_payments_debt', table_name='debt_payments')
    op.drop_index('ix_debt_payments_client', table_name='debt_payments')
    op.drop_table('debt_payments')
    op.drop_index('ix_sale_items_sale', table_name='sale_items')
    op.drop_index('ix_sale_items_product', table_name='sale_items')
    op.drop_index('ix_sale_items_batch', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_inventory_items_product', table_name='inventory_items')
    op.drop_index('ix_inventory_items_inventory', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index('ix_financial_transactions_type_category', table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_transaction_date'), table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_tenant_date', table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_category'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    op.drop_index('ix_debts_tenant_status', table_name='debts')
    op.drop_index('ix_debts_tenant_sale', table_name='debts')
    op.drop_index('ix_debts_tenant_due_date', table_name='debts')
    op.drop_index('ix_debts_tenant_client', table_name='debts')
    op.drop_table('debts')
    op.drop_index('ix_costs_tenant_supplier', table_name='costs')
    op.drop_index('ix_costs_tenant_status', table_name='costs')
    op.drop_index(op.f('ix_costs_tenant_id'), table_name='costs')
    op.drop_index('ix_costs_tenant_date', table_name='costs')
    op.drop_index('ix_costs_tenant_created_by', table_name='costs')
    op.drop_index('ix_costs_tenant_category', table_name='costs')
    op.drop_index('ix_costs_tenant_budget', table_name='costs')
    op.drop_index(op.f('ix_costs_reference'), table_name='costs')
    op.drop_table('costs')
    op.drop_index('ix_sales_tenant_status', table_name='sales')
    op.drop_index('ix_sales_tenant_payment', table_name='sales')
    op.drop_index('ix_sales_tenant_credit', table_name='sales')
    op.drop_index('ix_sales_tenant_created', table_name='sales')
    op.drop_index('ix_sales_tenant_client', table_name='sales')
    op.drop_index(op.f('ix_sales_reference'), table_name='sales')
    op.drop_index('ix_sales_created_by', table_name='sales')
    op.drop_index(op.f('ix_sales_created_at'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_physical_inventories_inventory_number'), table_name='physical_inventories')
    op.drop_index('ix_inventories_tenant_status', table_name='physical_inventories')
    op.drop_index('ix_inventories_tenant_date', table_name='physical_inventories')
    op.drop_table('physical_inventories')
    op.drop_index('ix_financial_periods_tenant_period', table_name='financial_periods')
    op.drop_index('ix_financial_periods_period_range', table_name='financial_periods')
    op.drop_table('financial_periods')
    op.drop_table('capitals')
    op.drop_index('ix_budgets_tenant_status', table_name='budgets')
    op.drop_index('ix_budgets_tenant_period', table_name='budgets')
    op.drop_index(op.f('ix_budgets_tenant_id'), table_name='budgets')
    op.drop_index('ix_budgets_tenant_category', table_name='budgets')
    op.drop_index(op.f('ix_budgets_code'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('sync_logs')
    op.drop_index('ix_suppliers_tenant_type', table_name='suppliers')
    op.drop_index('ix_suppliers_tenant_status', table_name='suppliers')
    op.drop_index('ix_suppliers_tenant_rating', table_name='suppliers')
    op.drop_index('ix_suppliers_tenant_name', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    op.drop_index('ix_suppliers_tenant_code', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_code'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index('ix_products_tenant_active', table_name='products')
    op.drop_index('ix_products_stock_status', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_index(op.f('ix_products_is_available'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index('ix_products_expiry_status', table_name='products')
    op.drop_index('ix_products_expiry_date', table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_table('inventory_schedules')
    op.drop_index('ix_clients_type', table_name='clients')
    op.drop_index('ix_clients_tenant_phone', table_name='clients')
    op.drop_index('ix_clients_tenant_nom', table_name='clients')
    op.drop_index('ix_clients_tenant_email', table_name='clients')
    op.drop_index('ix_clients_last_purchase', table_name='clients')
    op.drop_index('ix_clients_credit_status', table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_tenants_statut', table_name='tenants')
    op.drop_index('ix_tenants_plan', table_name='tenants')
    op.drop_index('ix_tenants_nom_pharmacie', table_name='tenants')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.drop_index('ix_tenants_domaine', table_name='tenants')
    op.drop_index('ix_tenants_date_creation', table_name='tenants')
    op.drop_index('ix_tenants_api_key', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
