"""modify_sale

Revision ID: 60f2eb2b4922
Revises: 1668f9ff34a3
Create Date: 2026-03-23 14:46:34.345258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60f2eb2b4922'
down_revision: Union[str, Sequence[str], None] = '1668f9ff34a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_counts', 'pharmacy_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('sales', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('sales', sa.Column('cancelled_by', sa.UUID(), nullable=True))
    op.add_column('sales', sa.Column('cancel_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'sales', 'users', ['cancelled_by'], ['id'])
    op.alter_column('stock_adjustment_items', 'old_quantity',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_adjustment_items', 'new_quantity',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_adjustment_items', 'quantity_change',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_adjustment_items', 'old_value',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_adjustment_items', 'new_value',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_adjustment_items', 'value_change',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_stock_adjustment_items_adjustment_id'), 'stock_adjustment_items', ['adjustment_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustment_items_product_id'), 'stock_adjustment_items', ['product_id'], unique=False)
    op.alter_column('stock_adjustments', 'adjustment_type',
               existing_type=sa.VARCHAR(length=50),
               comment='manual, auto, inventory, expiry, damage, loss, return',
               existing_nullable=False)
    op.alter_column('stock_adjustments', 'total_quantity_change',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_adjustments', 'total_value_change',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_adjustments', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='pending, approved, rejected, cancelled',
               existing_nullable=False)
    op.drop_constraint(op.f('stock_adjustments_adjustment_number_key'), 'stock_adjustments', type_='unique')
    op.create_foreign_key(None, 'stock_adjustments', 'inventory_counts', ['inventory_count_id'], ['id'])
    op.create_foreign_key(None, 'stock_adjustments', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'stock_adjustments', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'stock_adjustments', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'stock_adjustments', 'inventory_count_items', ['inventory_count_item_id'], ['id'])
    op.create_foreign_key(None, 'stock_adjustments', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'stock_adjustments', 'pharmacies', ['pharmacy_id'], ['id'])
    op.alter_column('stock_movements', 'pharmacy_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('stock_movements', 'purchase_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment="Prix d'achat",
               existing_nullable=True)
    op.alter_column('stock_movements', 'selling_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='Prix de vente',
               existing_nullable=True)
    op.alter_column('stock_movements', 'direction',
               existing_type=sa.VARCHAR(length=10),
               comment='in, out, adjustment',
               existing_nullable=True)
    op.alter_column('stock_movements', 'transfer_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='pending, in_transit, completed, cancelled',
               existing_nullable=True)
    op.alter_column('stock_movements', 'is_validated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('stock_movements', 'movement_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_movement_type'), table_name='stock_movements')
    op.alter_column('stock_movements', 'movement_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('stock_movements', 'is_validated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('stock_movements', 'transfer_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               comment=None,
               existing_comment='pending, in_transit, completed, cancelled',
               existing_nullable=True)
    op.alter_column('stock_movements', 'direction',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='in, out, adjustment',
               existing_nullable=True)
    op.alter_column('stock_movements', 'selling_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment=None,
               existing_comment='Prix de vente',
               existing_nullable=True)
    op.alter_column('stock_movements', 'purchase_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment=None,
               existing_comment="Prix d'achat",
               existing_nullable=True)
    op.alter_column('stock_movements', 'pharmacy_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'stock_adjustments', type_='foreignkey')
    op.drop_constraint(None, 'stock_adjustments', type_='foreignkey')
    op.drop_constraint(None, 'stock_adjustments', type_='foreignkey')
    op.drop_constraint(None, 'stock_adjustments', type_='foreignkey')
    op.drop_constraint(None, 'stock_adjustments', type_='foreignkey')
    op.drop_constraint(None, 'stock_adjustments', type_='foreignkey')
    op.drop_constraint(None, 'stock_adjustments', type_='foreignkey')
    op.create_unique_constraint(op.f('stock_adjustments_adjustment_number_key'), 'stock_adjustments', ['adjustment_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('stock_adjustments', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               comment=None,
               existing_comment='pending, approved, rejected, cancelled',
               existing_nullable=False)
    op.alter_column('stock_adjustments', 'total_value_change',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('stock_adjustments', 'total_quantity_change',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('stock_adjustments', 'adjustment_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='manual, auto, inventory, expiry, damage, loss, return',
               existing_nullable=False)
    op.drop_index(op.f('ix_stock_adjustment_items_product_id'), table_name='stock_adjustment_items')
    op.drop_index(op.f('ix_stock_adjustment_items_adjustment_id'), table_name='stock_adjustment_items')
    op.alter_column('stock_adjustment_items', 'value_change',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('stock_adjustment_items', 'new_value',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('stock_adjustment_items', 'old_value',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('stock_adjustment_items', 'quantity_change',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('stock_adjustment_items', 'new_quantity',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('stock_adjustment_items', 'old_quantity',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'cancel_reason')
    op.drop_column('sales', 'cancelled_by')
    op.drop_column('sales', 'cancelled_at')
    op.alter_column('inventory_counts', 'pharmacy_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
