"""add_ForeignKey_to_Sale

Revision ID: 81a26a41bf70
Revises: 654e13e30000
Create Date: 2026-03-18 02:03:13.338036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a26a41bf70'
down_revision: Union[str, Sequence[str], None] = '654e13e30000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'customer_id')
    # ### end Alembic commands ###
