"""update subscription and tenant models

Revision ID: 8f6d6ca5fc87
Revises: 12138e01f7b9
Create Date: 2025-12-21 08:45:42.704832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f6d6ca5fc87'
down_revision: Union[str, Sequence[str], None] = '12138e01f7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('payment_code', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'MOBILE_MONEY', 'BANK_TRANSFER', 'CARD', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payment_code'), 'payments', ['payment_code'], unique=True)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.add_column('subscriptions', sa.Column('subscription_code', sa.String(length=50), nullable=False))
    subscription_plan_enum = sa.Enum('STARTER','PROFESSIONAL','ENTERPRISE','ESSAI',name='subscriptionplan')
    subscription_plan_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'subscriptions',
        sa.Column(
            'plan',
            subscription_plan_enum,
            nullable=False
        )
    )
    billing_period_enum = sa.Enum(
    'MENSUEL',
    'ANNUEL',
    'TRIMESTRIEL',
    name='billingperiod'
    )

    billing_period_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('subscriptions',sa.Column('billing_period',billing_period_enum, nullable=False))
    subscription_status_enum = sa.Enum(
    'ACTIVE',
    'PENDING',
    'TRIAL',
    'EXPIRED',
    'SUSPENDED',
    'CANCELLED',
    name='subscriptionstatus'
    )

    subscription_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('subscriptions',sa.Column('status',subscription_status_enum,nullable=False))

    op.add_column('subscriptions', sa.Column('monthly_price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('subscriptions', sa.Column('annual_price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('subscriptions', sa.Column('current_price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('subscriptions', sa.Column('tax_rate', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('subscriptions', sa.Column('discount_percent', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('subscriptions', sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('subscriptions', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('subscriptions', sa.Column('end_date', sa.DateTime(), nullable=False))
    op.add_column('subscriptions', sa.Column('trial_end_date', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('next_billing_date', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('cancellation_date', sa.DateTime(), nullable=True))
    op.add_column('subscriptions', sa.Column('max_users', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('max_products', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('max_storage_mb', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('features', sa.Text(), nullable=True))
    op.add_column('subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('subscriptions', sa.Column('meta_data', sa.Text(), nullable=True))
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('subscriptions', sa.Column('created_by', sa.UUID(), nullable=True))
    op.alter_column('subscriptions', 'plan_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_subscriptions_subscription_code'), 'subscriptions', ['subscription_code'], unique=True)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'users', ['created_by'], ['id'])
    op.drop_column('subscriptions', 'date_debut')
    op.drop_column('subscriptions', 'date_fin')
    op.drop_column('subscriptions', 'prix')
    op.drop_column('subscriptions', 'statut')
    op.add_column('tenants', sa.Column('tenant_code', sa.String(length=20), nullable=False, comment='Code unique de la pharmacie (ex: PHARMA-001)'))
    op.add_column('tenants', sa.Column('slug', sa.String(length=100), nullable=True, comment='Slug pour URLs personnalisées'))
    op.add_column('tenants', sa.Column('nom_commercial', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('slogan', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('email_admin', sa.String(length=150), nullable=False, comment="Email principal de l'administrateur"))
    op.add_column('tenants', sa.Column('email_contact', sa.String(length=150), nullable=True))
    op.add_column('tenants', sa.Column('telephone_principal', sa.String(length=20), nullable=False))
    op.add_column('tenants', sa.Column('telephone_mobile', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('fax', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('adresse_ligne1', sa.String(length=200), nullable=False))
    op.add_column('tenants', sa.Column('adresse_ligne2', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('code_postal', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True))
    op.add_column('tenants', sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True))
    op.add_column('tenants', sa.Column('forme_juridique', sa.String(length=50), nullable=True, comment='SARL, SA, EI, etc.'))
    op.add_column('tenants', sa.Column('numero_ifu', sa.String(length=50), nullable=True, comment='Identification Fiscale Unique'))
    op.add_column('tenants', sa.Column('numero_national', sa.String(length=50), nullable=True, comment="Numéro national d'entreprise"))
    op.add_column('tenants', sa.Column('date_agrement', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('prenom_proprietaire', sa.String(length=150), nullable=True))
    op.add_column('tenants', sa.Column('email_proprietaire', sa.String(length=150), nullable=True))
    op.add_column('tenants', sa.Column('telephone_proprietaire', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('nom_pharmacien', sa.String(length=150), nullable=True))
    op.add_column('tenants', sa.Column('prenom_pharmacien', sa.String(length=150), nullable=True))
    op.add_column('tenants', sa.Column('numero_ordre', sa.String(length=50), nullable=True, comment="Numéro d'ordre du pharmacien"))
    op.add_column('tenants', sa.Column('email_pharmacien', sa.String(length=150), nullable=True))
    op.add_column('tenants', sa.Column('telephone_pharmacien', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('nombre_guichets', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('annee_creation', sa.Integer(), nullable=True, comment='Année de création de la pharmacie'))
    op.add_column('tenants', sa.Column('horaires', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tenants', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('tenants', sa.Column('current_plan', sa.String(length=50), nullable=True, comment="Plan d'abonnement actuel (starter, professional, enterprise)"))
    op.add_column('tenants', sa.Column('billing_period', sa.String(length=20), nullable=True, comment='monthly, quarterly, annual'))
    op.add_column('tenants', sa.Column('subscription_start_date', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('trial_start_date', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('trial_end_date', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('last_payment_date', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('next_payment_date', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('monthly_rate', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('tenants', sa.Column('annual_rate', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('tenants', sa.Column('current_rate', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('tenants', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('payment_method', sa.String(length=50), nullable=True, comment='mobile_money, bank_transfer, card, cash'))
    op.add_column('tenants', sa.Column('devise_symbol', sa.String(length=10), nullable=True))
    op.add_column('tenants', sa.Column('decimal_places', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('favicon_url', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('couleur_secondaire', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('page_facebook', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('compte_twitter', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('compte_instagram', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('api_secret', sa.String(length=200), nullable=True))
    op.add_column('tenants', sa.Column('custom_domain', sa.String(length=150), nullable=True))
    op.add_column('tenants', sa.Column('ssl_enabled', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('ip_restrictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Liste d'IP autorisées"))
    op.add_column('tenants', sa.Column('mfa_required', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('max_users', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('max_products', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('max_customers', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('max_storage_mb', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('max_api_calls_per_day', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('total_sales', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('total_revenue', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('tenants', sa.Column('total_customers', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('total_products', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('total_inventory_value', sa.DECIMAL(precision=15, scale=2), nullable=True))
    op.add_column('tenants', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tenants', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tenants', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('tenants', sa.Column('activated_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('suspended_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('last_sync_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('last_backup_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('tenants', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('tenants', 'pays',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('tenants', 'nom_entreprise',
               existing_type=sa.VARCHAR(length=200),
               comment="Nom légal de l'entreprise",
               existing_nullable=True)
    op.alter_column('tenants', 'numero_agrement',
               existing_type=sa.VARCHAR(length=50),
               comment="Numéro d'agrément pharmaceutique",
               existing_nullable=True)
    op.alter_column('tenants', 'type_pharmacie',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               comment=None,
               existing_comment='officine, hospitaliere, veterinaire, parapharmacie')
    
    op.alter_column(
        'tenants',
        'superficie',
        existing_type=sa.VARCHAR(length=50),
        type_=sa.DECIMAL(precision=10, scale=2),
        postgresql_using="superficie::numeric(10,2)", 
        comment='Superficie en m²',
        existing_nullable=True
    )

    op.execute("""
        UPDATE tenants
        SET nombre_employes = NULL
        WHERE nombre_employes !~ '^[0-9]+$'
    """)

    op.alter_column(
        'tenants',
        'nombre_employes',
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Integer(),
        postgresql_using="nombre_employes::integer",
        existing_nullable=True,
        comment="Nombre d’employés de la pharmacie")
    
    op.alter_column('tenants', 'config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_tenants_api_key'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_date_creation'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_domaine'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_plan'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_statut'), table_name='tenants')
    op.drop_constraint(op.f('tenants_domaine_personnalise_key'), 'tenants', type_='unique')
    op.create_index('idx_tenants_geo', 'tenants', ['pays', 'province', 'ville'], unique=False)
    op.create_index('idx_tenants_slug', 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenants_current_plan'), 'tenants', ['current_plan'], unique=False)
    op.create_index(op.f('ix_tenants_email_admin'), 'tenants', ['email_admin'], unique=False)
    op.create_index('ix_tenants_nom_proprietaire', 'tenants', ['nom_proprietaire'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_index('ix_tenants_telephone_principal', 'tenants', ['telephone_principal'], unique=False)
    op.create_index(op.f('ix_tenants_tenant_code'), 'tenants', ['tenant_code'], unique=True)
    op.create_index('ix_tenants_ville', 'tenants', ['ville'], unique=False)
    op.create_unique_constraint(None, 'tenants', ['numero_ifu'])
    op.create_unique_constraint(None, 'tenants', ['registre_commerce'])
    op.create_unique_constraint(None, 'tenants', ['custom_domain'])
    op.create_foreign_key(None, 'tenants', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'tenants', 'users', ['updated_by'], ['id'])
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'plan_abonnement')
    op.drop_column('tenants', 'date_prochain_paiement')
    op.drop_column('tenants', 'telephone')
    op.drop_column('tenants', 'num_contribuable')
    op.drop_column('tenants', 'montant_abonnement')
    op.drop_column('tenants', 'domaine_personnalise')
    op.drop_column('tenants', 'date_creation')
    op.drop_column('tenants', 'date_modification')
    op.drop_column('tenants', 'ssl_actif')
    op.drop_column('tenants', 'date_desactivation')
    op.drop_column('tenants', 'date_fin_essai')
    op.drop_column('tenants', 'date_debut_abonnement')
    op.drop_column('tenants', 'statut')
    op.drop_column('tenants', 'id_nat')
    op.drop_column('tenants', 'adresse')
    op.drop_column('tenants', 'jours_ouverture')
    op.drop_column('tenants', 'derniere_connexion')
    op.drop_column('tenants', 'reseaux_sociaux')
    op.drop_column('tenants', 'periode_facturation')
    op.drop_column('tenants', 'heures_ouverture')
    op.drop_column('tenants', 'tenant_metadata')
    op.drop_column('tenants', 'date_activation')
    op.drop_column('tenants', 'coordonnees_gps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('coordonnees_gps', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Latitude,Longitude'))
    op.add_column('tenants', sa.Column('date_activation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('tenant_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('heures_ouverture', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('periode_facturation', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('reseaux_sociaux', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('derniere_connexion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('jours_ouverture', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('adresse', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('id_nat', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment="Numéro d'identification nationale"))
    op.add_column('tenants', sa.Column('statut', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='essai, actif, suspendu, expire, resiliation'))
    op.add_column('tenants', sa.Column('date_debut_abonnement', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('date_fin_essai', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('date_desactivation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('ssl_actif', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('date_modification', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('domaine_personnalise', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('montant_abonnement', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('num_contribuable', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Numéro de contribuable'))
    op.add_column('tenants', sa.Column('telephone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('date_prochain_paiement', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('plan_abonnement', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_index('ix_tenants_ville', table_name='tenants')
    op.drop_index(op.f('ix_tenants_tenant_code'), table_name='tenants')
    op.drop_index('ix_tenants_telephone_principal', table_name='tenants')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index('ix_tenants_nom_proprietaire', table_name='tenants')
    op.drop_index(op.f('ix_tenants_email_admin'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_current_plan'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.drop_index('idx_tenants_slug', table_name='tenants')
    op.drop_index('idx_tenants_geo', table_name='tenants')
    op.create_unique_constraint(op.f('tenants_domaine_personnalise_key'), 'tenants', ['domaine_personnalise'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tenants_statut'), 'tenants', ['statut'], unique=False)
    op.create_index(op.f('ix_tenants_plan'), 'tenants', ['plan_abonnement'], unique=False)
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=False)
    op.create_index(op.f('ix_tenants_domaine'), 'tenants', ['domaine_personnalise'], unique=False)
    op.create_index(op.f('ix_tenants_date_creation'), 'tenants', ['date_creation'], unique=False)
    op.create_index(op.f('ix_tenants_api_key'), 'tenants', ['api_key'], unique=False)
    op.alter_column('tenants', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column(
            'tenants',
            'nombre_employes',
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True
        )
    op.execute("""
                UPDATE tenants
                SET superficie = NULL
                WHERE superficie !~ '^[0-9]+(\\.[0-9]+)?$'
            """)

    op.alter_column(
            'tenants',
            'superficie',
            existing_type=sa.VARCHAR(length=50),
            type_=sa.DECIMAL(10, 2),
            postgresql_using="superficie::numeric(10,2)",
            comment='Superficie en m²',
            existing_nullable=True)


    op.alter_column('tenants', 'type_pharmacie',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               comment='officine, hospitaliere, veterinaire, parapharmacie')
    op.alter_column('tenants', 'numero_agrement',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Numéro d'agrément pharmaceutique",
               existing_nullable=True)
    op.alter_column('tenants', 'nom_entreprise',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment="Nom légal de l'entreprise",
               existing_nullable=True)
    op.alter_column('tenants', 'pays',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('tenants', 'updated_by')
    op.drop_column('tenants', 'created_by')
    op.drop_column('tenants', 'last_backup_at')
    op.drop_column('tenants', 'last_sync_at')
    op.drop_column('tenants', 'last_login_at')
    op.drop_column('tenants', 'archived_at')
    op.drop_column('tenants', 'cancelled_at')
    op.drop_column('tenants', 'suspended_at')
    op.drop_column('tenants', 'activated_at')
    op.drop_column('tenants', 'updated_at')
    op.drop_column('tenants', 'created_at')
    op.drop_column('tenants', 'tags')
    op.drop_column('tenants', 'meta_data')
    op.drop_column('tenants', 'total_inventory_value')
    op.drop_column('tenants', 'total_products')
    op.drop_column('tenants', 'total_customers')
    op.drop_column('tenants', 'total_revenue')
    op.drop_column('tenants', 'total_sales')
    op.drop_column('tenants', 'max_api_calls_per_day')
    op.drop_column('tenants', 'max_storage_mb')
    op.drop_column('tenants', 'max_customers')
    op.drop_column('tenants', 'max_products')
    op.drop_column('tenants', 'max_users')
    op.drop_column('tenants', 'mfa_required')
    op.drop_column('tenants', 'ip_restrictions')
    op.drop_column('tenants', 'ssl_enabled')
    op.drop_column('tenants', 'custom_domain')
    op.drop_column('tenants', 'api_secret')
    op.drop_column('tenants', 'compte_instagram')
    op.drop_column('tenants', 'compte_twitter')
    op.drop_column('tenants', 'page_facebook')
    op.drop_column('tenants', 'couleur_secondaire')
    op.drop_column('tenants', 'favicon_url')
    op.drop_column('tenants', 'decimal_places')
    op.drop_column('tenants', 'devise_symbol')
    op.drop_column('tenants', 'payment_method')
    op.drop_column('tenants', 'auto_renew')
    op.drop_column('tenants', 'current_rate')
    op.drop_column('tenants', 'annual_rate')
    op.drop_column('tenants', 'monthly_rate')
    op.drop_column('tenants', 'next_payment_date')
    op.drop_column('tenants', 'last_payment_date')
    op.drop_column('tenants', 'trial_end_date')
    op.drop_column('tenants', 'trial_start_date')
    op.drop_column('tenants', 'subscription_end_date')
    op.drop_column('tenants', 'subscription_start_date')
    op.drop_column('tenants', 'billing_period')
    op.drop_column('tenants', 'current_plan')
    op.drop_column('tenants', 'status')
    op.drop_column('tenants', 'horaires')
    op.drop_column('tenants', 'annee_creation')
    op.drop_column('tenants', 'nombre_guichets')
    op.drop_column('tenants', 'telephone_pharmacien')
    op.drop_column('tenants', 'email_pharmacien')
    op.drop_column('tenants', 'numero_ordre')
    op.drop_column('tenants', 'prenom_pharmacien')
    op.drop_column('tenants', 'nom_pharmacien')
    op.drop_column('tenants', 'telephone_proprietaire')
    op.drop_column('tenants', 'email_proprietaire')
    op.drop_column('tenants', 'prenom_proprietaire')
    op.drop_column('tenants', 'date_agrement')
    op.drop_column('tenants', 'numero_national')
    op.drop_column('tenants', 'numero_ifu')
    op.drop_column('tenants', 'forme_juridique')
    op.drop_column('tenants', 'longitude')
    op.drop_column('tenants', 'latitude')
    op.drop_column('tenants', 'code_postal')
    op.drop_column('tenants', 'adresse_ligne2')
    op.drop_column('tenants', 'adresse_ligne1')
    op.drop_column('tenants', 'fax')
    op.drop_column('tenants', 'telephone_mobile')
    op.drop_column('tenants', 'telephone_principal')
    op.drop_column('tenants', 'email_contact')
    op.drop_column('tenants', 'email_admin')
    op.drop_column('tenants', 'description')
    op.drop_column('tenants', 'slogan')
    op.drop_column('tenants', 'nom_commercial')
    op.drop_column('tenants', 'slug')
    op.drop_column('tenants', 'tenant_code')
    op.add_column('subscriptions', sa.Column('statut', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('prix', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('date_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('date_debut', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_subscription_code'), table_name='subscriptions')
    op.alter_column('subscriptions', 'plan_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('subscriptions', 'created_by')
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'meta_data')
    op.drop_column('subscriptions', 'notes')
    op.drop_column('subscriptions', 'auto_renew')
    op.drop_column('subscriptions', 'features')
    op.drop_column('subscriptions', 'max_storage_mb')
    op.drop_column('subscriptions', 'max_products')
    op.drop_column('subscriptions', 'max_users')
    op.drop_column('subscriptions', 'cancellation_date')
    op.drop_column('subscriptions', 'next_billing_date')
    op.drop_column('subscriptions', 'trial_end_date')
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'discount_amount')
    op.drop_column('subscriptions', 'discount_percent')
    op.drop_column('subscriptions', 'tax_rate')
    op.drop_column('subscriptions', 'current_price')
    op.drop_column('subscriptions', 'annual_price')
    op.drop_column('subscriptions', 'monthly_price')
    op.drop_column('subscriptions', 'status')
    op.drop_column('subscriptions', 'billing_period')
    op.drop_column('subscriptions', 'plan')

    subscription_plan_enum = sa.Enum(
        'STARTER',
        'PROFESSIONAL',
        'ENTERPRISE',
        'ESSAI',
        name='subscriptionplan'
    )

    subscription_plan_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('subscriptions', 'subscription_code')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_code'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
