"""add_expense_table

Revision ID: b67db3eab64f
Revises: a4d879be94aa
Create Date: 2026-04-19 21:18:00.013708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b67db3eab64f'
down_revision: Union[str, Sequence[str], None] = 'a4d879be94aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('expense_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('is_reimbursed', sa.Boolean(), nullable=True),
    sa.Column('reimbursement_date', sa.Date(), nullable=True),
    sa.Column('reimbursement_reference', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True, comment='URL de la pièce jointe'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_expenses_branch_id'), 'user_expenses', ['branch_id'], unique=False)
    op.create_index('ix_user_expenses_reimbursed', 'user_expenses', ['is_reimbursed', 'tenant_id'], unique=False)
    op.create_index(op.f('ix_user_expenses_tenant_id'), 'user_expenses', ['tenant_id'], unique=False)
    op.create_index('ix_user_expenses_tenant_user', 'user_expenses', ['tenant_id', 'user_id'], unique=False)
    op.create_index('ix_user_expenses_user_date', 'user_expenses', ['user_id', 'expense_date'], unique=False)
    op.create_index(op.f('ix_user_expenses_user_id'), 'user_expenses', ['user_id'], unique=False)
    op.drop_table('subscriptions_backup_20260419')
    op.drop_index(op.f('idx_sync_feedback_user_read'), table_name='sync_feedback')
    op.drop_table('sync_feedback')
    
    op.add_column('expenses', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.add_column('expenses', sa.Column('user_id', sa.UUID(), nullable=True, comment='Utilisateur qui a généré la dépense'))
    op.add_column('expenses', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('expenses', sa.Column('approval_status', sa.String(length=20), nullable=True, comment='pending, approved, rejected'))
    op.add_column('expenses', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('expenses', sa.Column('cost_center', sa.String(length=100), nullable=True, comment='Centre de coût'))
    op.add_column('expenses', sa.Column('project_code', sa.String(length=50), nullable=True, comment='Code projet si applicable'))
    op.create_index('ix_expenses_approval_status', 'expenses', ['tenant_id', 'approval_status'], unique=False)
    op.create_index('ix_expenses_branch_date', 'expenses', ['branch_id', 'expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_branch_id'), 'expenses', ['branch_id'], unique=False)
    op.create_index('ix_expenses_tenant_branch', 'expenses', ['tenant_id', 'branch_id'], unique=False)
    op.create_index('ix_expenses_tenant_user', 'expenses', ['tenant_id', 'user_id'], unique=False)
    op.create_index('ix_expenses_user_date', 'expenses', ['user_id', 'expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'branches', ['branch_id'], ['id'])
    
    op.alter_column('products', 'stock_version',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_products_stock_version'), table_name='products')
    op.drop_index(op.f('idx_sales_is_rejected'), table_name='sales')
    op.drop_index(op.f('idx_sales_is_synced'), table_name='sales')
    op.drop_column('sales', 'device_id')
    op.drop_column('sales', 'rejection_reason')
    op.drop_column('sales', 'is_partial')
    op.drop_column('sales', 'stock_version_at_sale')
    op.drop_column('sales', 'is_rejected')
    op.drop_column('sales', 'rejected_quantity')
    op.drop_column('sales', 'is_synced')
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_foreign_key(op.f('subscription_codes_tenant_id_fkey'), 'subscription_codes', 'tenants', ['tenant_id'], ['id'])
    op.add_column('sales', sa.Column('is_synced', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('rejected_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('is_rejected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('stock_version_at_sale', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('is_partial', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sales', sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_sales_is_synced'), 'sales', ['is_synced'], unique=False)
    op.create_index(op.f('idx_sales_is_rejected'), 'sales', ['is_rejected'], unique=False)
    op.create_index(op.f('idx_products_stock_version'), 'products', ['stock_version'], unique=False)
    op.alter_column('products', 'stock_version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)
    
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index('ix_expenses_user_date', table_name='expenses')
    op.drop_index('ix_expenses_tenant_user', table_name='expenses')
    op.drop_index('ix_expenses_tenant_branch', table_name='expenses')
    op.drop_index(op.f('ix_expenses_branch_id'), table_name='expenses')
    op.drop_index('ix_expenses_branch_date', table_name='expenses')
    op.drop_index('ix_expenses_approval_status', table_name='expenses')
    op.drop_column('expenses', 'project_code')
    op.drop_column('expenses', 'cost_center')
    op.drop_column('expenses', 'rejection_reason')
    op.drop_column('expenses', 'approval_status')
    op.drop_column('expenses', 'approved_by')
    op.drop_column('expenses', 'user_id')
    op.drop_column('expenses', 'branch_id')
    
    op.create_table('sync_feedback',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('sale_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('feedback_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_feedback_pkey'))
    )
    op.create_index(op.f('idx_sync_feedback_user_read'), 'sync_feedback', ['user_id', 'is_read'], unique=False)
    op.create_table('subscriptions_backup_20260419',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subscription_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('plan_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('billing_period', postgresql.ENUM('MENSUEL', 'ANNUEL', 'TRIMESTRIEL', name='billingperiod'), autoincrement=False, nullable=True),
    sa.Column('monthly_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('annual_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('discount_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('trial_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_billing_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cancellation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('max_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_products', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_storage_mb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('features', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('auto_renew', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_user_expenses_user_id'), table_name='user_expenses')
    op.drop_index('ix_user_expenses_user_date', table_name='user_expenses')
    op.drop_index('ix_user_expenses_tenant_user', table_name='user_expenses')
    op.drop_index(op.f('ix_user_expenses_tenant_id'), table_name='user_expenses')
    op.drop_index('ix_user_expenses_reimbursed', table_name='user_expenses')
    op.drop_index(op.f('ix_user_expenses_branch_id'), table_name='user_expenses')
    op.drop_table('user_expenses')
    # ### end Alembic commands ###
