"""update_code

Revision ID: b9a77f62da73
Revises: 5af9d5a70964
Create Date: 2026-03-23 09:00:48.208974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a77f62da73'
down_revision: Union[str, Sequence[str], None] = '5af9d5a70964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_movements', 'movement_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='initial, purchase, sale, adjustment, return, transfer, expiry, correction',
               existing_nullable=False)
    op.drop_index(op.f('idx_stock_movements_sale_id'), table_name='stock_movements')
    op.drop_index(op.f('idx_stock_movements_sale_item_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_type'), table_name='stock_movements')
    op.drop_constraint(op.f('fk_stock_movements_sale_item_id'), 'stock_movements', type_='foreignkey')
    op.drop_constraint(op.f('fk_stock_movements_sale_id'), 'stock_movements', type_='foreignkey')
    op.create_foreign_key(None, 'stock_movements', 'sale_items', ['sale_item_id'], ['id'])
    op.create_foreign_key(None, 'stock_movements', 'sales', ['sale_id'], ['id'])
    op.add_column('subscription_codes', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('subscription_codes', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'subscription_codes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'subscription_codes', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.drop_constraint(None, 'subscription_codes', type_='foreignkey')
    op.drop_constraint(None, 'subscription_codes', type_='foreignkey')
    op.drop_column('subscription_codes', 'user_id')
    op.drop_column('subscription_codes', 'tenant_id')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.create_foreign_key(op.f('fk_stock_movements_sale_id'), 'stock_movements', 'sales', ['sale_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_stock_movements_sale_item_id'), 'stock_movements', 'sale_items', ['sale_item_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    op.create_index(op.f('idx_stock_movements_sale_item_id'), 'stock_movements', ['sale_item_id'], unique=False)
    op.create_index(op.f('idx_stock_movements_sale_id'), 'stock_movements', ['sale_id'], unique=False)
    op.alter_column('stock_movements', 'movement_type',
               existing_type=sa.VARCHAR(length=50),
               comment='initial, purchase, sale, adjustment, return, transfer, expiry, correction',
               existing_nullable=False)
    # ### end Alembic commands ###
