"""add_pharmacy_id_to_purchases

Revision ID: bba2b861ecdd
Revises: 32511c8b91dc
Create Date: 2026-03-18 00:44:40.450367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba2b861ecdd'
down_revision: Union[str, Sequence[str], None] = '32511c8b91dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('pharmacy_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_purchases_pharmacy_id'), 'purchases', ['pharmacy_id'], unique=False)
    op.create_foreign_key(None, 'purchases', 'pharmacies', ['pharmacy_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_index(op.f('ix_purchases_pharmacy_id'), table_name='purchases')
    op.drop_column('purchases', 'pharmacy_id')
    # ### end Alembic commands ###
