"""add_ForeignKey_to_branch

Revision ID: bbbe2a94de2b
Revises: 81a26a41bf70
Create Date: 2026-03-18 02:25:28.527296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbbe2a94de2b'
down_revision: Union[str, Sequence[str], None] = '81a26a41bf70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'customers', 'branches', ['branch_id'], ['id'])
    op.add_column('products', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'branches', ['branch_id'], ['id'])
    op.add_column('sales', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sales', 'branches', ['branch_id'], ['id'])
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=False)
    op.drop_index(op.f('ix_tenants_tenant_code'), table_name='tenants')
    op.create_index('ix_tenants_tenant_code', 'tenants', ['tenant_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenants_tenant_code', table_name='tenants')
    op.create_index(op.f('ix_tenants_tenant_code'), 'tenants', ['tenant_code'], unique=True)
    op.drop_index('ix_tenants_slug', table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'branch_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'branch_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'branch_id')
    # ### end Alembic commands ###
