"""add_selling_price_retail_wholesale_to_products

Revision ID: cd027ced3934
Revises: f549dda78313
Create Date: 2026-04-03 09:51:29.908100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd027ced3934'
down_revision: Union[str, Sequence[str], None] = 'f549dda78313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('pharmacy_configs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pharmacy_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'calcul_auto_prix',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'marge_par_defaut',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'sales_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'taux_tva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'rounding_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'rounding_precision',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'rounding_method',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'exchange_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'primary_currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.add_column('products', sa.Column('selling_price_retail', sa.Numeric(precision=12, scale=2), nullable=True, comment='Prix de vente au détail'))
    op.add_column('products', sa.Column('selling_price_wholesale', sa.Numeric(precision=12, scale=2), nullable=True, comment='Prix de vente en gros'))
    op.drop_index(op.f('idx_products_branch'), table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_products_branch'), 'products', ['branch_id'], unique=False)
    op.drop_column('products', 'selling_price_wholesale')
    op.drop_column('products', 'selling_price_retail')
    op.alter_column('pharmacy_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'primary_currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'CDF'::character varying"),
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'exchange_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('1.0'),
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'rounding_method',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'nearest'::character varying"),
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'rounding_precision',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'rounding_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'taux_tva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'sales_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'both'::character varying"),
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'marge_par_defaut',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('30.0'),
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'calcul_auto_prix',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('pharmacy_configs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    