"""fix_product_stock_relation

Revision ID: cef3a6cd6ebd
Revises: 9b27a540858d
Create Date: 2026-02-27 23:02:20.764483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef3a6cd6ebd'
down_revision: Union[str, Sequence[str], None] = '9b27a540858d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('ix_inventory_items_product', 'inventory_items', ['tenant_id', 'product_id'], unique=False)
    op.add_column('stock_movements', sa.Column('product_stock_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'stock_movements', 'product_stocks', ['product_stock_id'], ['id'])
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.drop_index(op.f('ix_tenants_tenant_code'), table_name='tenants')
    op.create_index('ix_tenants_tenant_code', 'tenants', ['tenant_code'], unique=False)
    op.create_foreign_key('fk_tenants_created_by_users', 'tenants', 'users', ['created_by'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tenants_created_by_users', 'tenants', type_='foreignkey')
    op.drop_index('ix_tenants_tenant_code', table_name='tenants')
    op.create_index(op.f('ix_tenants_tenant_code'), 'tenants', ['tenant_code'], unique=True)
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_column('stock_movements', 'product_stock_id')
    op.drop_index('ix_inventory_items_product', table_name='inventory_items')
    # ### end Alembic commands ###
