"""add subscription models

Revision ID: d22c5349c3b8
Revises: d62706e95712
Create Date: 2026-03-19 20:57:13.844307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22c5349c3b8'
down_revision: Union[str, Sequence[str], None] = 'd62706e95712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVATED', 'EXPIRED', 'CANCELLED', name='subscriptioncodestatus'), nullable=True),
    sa.Column('activated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['activated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_codes_code'), 'subscription_codes', ['code'], unique=True)
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenants_slug', table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.drop_index(op.f('ix_subscription_codes_code'), table_name='subscription_codes')
    op.drop_table('subscription_codes')
    # ### end Alembic commands ###
