"""add_user_branch_model

Revision ID: d37cec63742e
Revises: c60f40653250
Create Date: 2026-04-27 15:45:35.324592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd37cec63742e'
down_revision: Union[str, Sequence[str], None] = 'c60f40653250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Create user_branches table only."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_branches',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('branch_id', sa.UUID(), nullable=False),
        sa.Column('role_in_branch', sa.String(length=50), nullable=True),
        sa.Column('permissions', sa.JSON(), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for better performance
    op.create_index('idx_user_branches_user_id', 'user_branches', ['user_id'])
    op.create_index('idx_user_branches_branch_id', 'user_branches', ['branch_id'])
    op.create_index('idx_user_branches_user_branch', 'user_branches', ['user_id', 'branch_id'], unique=True)
    op.create_index('idx_user_branches_primary', 'user_branches', ['user_id', 'is_primary'], unique=False, 
                    postgresql_where=sa.text('is_primary = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - Drop user_branches table only."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_branches_primary', table_name='user_branches')
    op.drop_index('idx_user_branches_user_branch', table_name='user_branches')
    op.drop_index('idx_user_branches_branch_id', table_name='user_branches')
    op.drop_index('idx_user_branches_user_id', table_name='user_branches')
    op.drop_table('user_branches')
    # ### end Alembic commands ###