"""refactor tenant model saas

Revision ID: f25f78aa5eda
Revises: 8f6d6ca5fc87
Create Date: 2025-12-22 11:44:02.835230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f25f78aa5eda'
down_revision: Union[str, Sequence[str], None] = '8f6d6ca5fc87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'tenant_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Code unique de la pharmacie (ex: PHARMA-001)',
               existing_nullable=False)
    op.alter_column('tenants', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Slug pour URLs personnalisées',
               existing_nullable=True)
    op.alter_column('tenants', 'email_admin',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment="Email principal de l'administrateur",
               existing_nullable=False)
    op.alter_column('tenants', 'pays',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tenants', 'type_pharmacie',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tenants', 'nombre_employes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Nombre d’employés de la pharmacie',
               existing_nullable=True)
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tenants', 'current_plan',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Plan d'abonnement actuel (starter, professional, enterprise)",
               existing_nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_tenants_geo'), table_name='tenants')
    op.drop_index(op.f('idx_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_current_plan'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_nom_pharmacie'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_nom_proprietaire'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_telephone_principal'), table_name='tenants')
    op.drop_constraint(op.f('tenants_api_key_key'), 'tenants', type_='unique')
    op.drop_constraint(op.f('tenants_custom_domain_key'), 'tenants', type_='unique')
    op.drop_constraint(op.f('tenants_numero_agrement_key'), 'tenants', type_='unique')
    op.drop_constraint(op.f('tenants_numero_ifu_key'), 'tenants', type_='unique')
    op.drop_constraint(op.f('tenants_registre_commerce_key'), 'tenants', type_='unique')
    op.create_index('ix_tenants_plan', 'tenants', ['current_plan'], unique=False)
    op.drop_constraint(op.f('tenants_updated_by_fkey'), 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'slogan')
    op.drop_column('tenants', 'prenom_proprietaire')
    op.drop_column('tenants', 'favicon_url')
    op.drop_column('tenants', 'billing_period')
    op.drop_column('tenants', 'email_contact')
    op.drop_column('tenants', 'quartier')
    op.drop_column('tenants', 'numero_ifu')
    op.drop_column('tenants', 'fuseau_horaire')
    op.drop_column('tenants', 'email_pharmacien')
    op.drop_column('tenants', 'format_heure')
    op.drop_column('tenants', 'code_postal')
    op.drop_column('tenants', 'last_sync_at')
    op.drop_column('tenants', 'longitude')
    op.drop_column('tenants', 'compte_instagram')
    op.drop_column('tenants', 'last_backup_at')
    op.drop_column('tenants', 'format_date')
    op.drop_column('tenants', 'telephone_proprietaire')
    op.drop_column('tenants', 'devise')
    op.drop_column('tenants', 'site_web')
    op.drop_column('tenants', 'nom_entreprise')
    op.drop_column('tenants', 'max_storage_mb')
    op.drop_column('tenants', 'horaires')
    op.drop_column('tenants', 'logo_url')
    op.drop_column('tenants', 'devise_symbol')
    op.drop_column('tenants', 'cancelled_at')
    op.drop_column('tenants', 'total_products')
    op.drop_column('tenants', 'email_proprietaire')
    op.drop_column('tenants', 'api_key')
    op.drop_column('tenants', 'custom_domain')
    op.drop_column('tenants', 'max_customers')
    op.drop_column('tenants', 'fax')
    op.drop_column('tenants', 'api_secret')
    op.drop_column('tenants', 'total_inventory_value')
    op.drop_column('tenants', 'next_payment_date')
    op.drop_column('tenants', 'couleur_secondaire')
    op.drop_column('tenants', 'annual_rate')
    op.drop_column('tenants', 'adresse_ligne1')
    op.drop_column('tenants', 'superficie')
    op.drop_column('tenants', 'couleur_principale')
    op.drop_column('tenants', 'total_customers')
    op.drop_column('tenants', 'current_rate')
    op.drop_column('tenants', 'total_sales')
    op.drop_column('tenants', 'prenom_pharmacien')
    op.drop_column('tenants', 'telephone_secondaire')
    op.drop_column('tenants', 'decimal_places')
    op.drop_column('tenants', 'telephone_pharmacien')
    op.drop_column('tenants', 'updated_by')
    op.drop_column('tenants', 'max_api_calls_per_day')
    op.drop_column('tenants', 'mfa_required')
    op.drop_column('tenants', 'page_facebook')
    op.drop_column('tenants', 'archived_at')
    op.drop_column('tenants', 'last_payment_date')
    op.drop_column('tenants', 'nom_pharmacien')
    op.drop_column('tenants', 'specialite')
    op.drop_column('tenants', 'registre_commerce')
    op.drop_column('tenants', 'last_login_at')
    op.drop_column('tenants', 'telephone_mobile')
    op.drop_column('tenants', 'numero_national')
    op.drop_column('tenants', 'total_revenue')
    op.drop_column('tenants', 'payment_method')
    op.drop_column('tenants', 'numero_agrement')
    op.drop_column('tenants', 'numero_ordre')
    op.drop_column('tenants', 'nombre_guichets')
    op.drop_column('tenants', 'compte_twitter')
    op.drop_column('tenants', 'ssl_enabled')
    op.drop_column('tenants', 'latitude')
    op.drop_column('tenants', 'forme_juridique')
    op.drop_column('tenants', 'langue')
    op.drop_column('tenants', 'ip_restrictions')
    op.drop_column('tenants', 'annee_creation')
    op.drop_column('tenants', 'adresse_ligne2')
    op.drop_column('tenants', 'date_agrement')
    op.drop_column('tenants', 'commune')
    op.add_column('users', sa.Column('sms_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('sms_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('reset_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'login_attempts')
    op.drop_column('users', 'reset_expires')
    op.drop_column('users', 'reset_code')
    op.drop_column('users', 'sms_expires_at')
    op.drop_column('users', 'sms_code')
    op.add_column('tenants', sa.Column('commune', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('date_agrement', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('adresse_ligne2', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('annee_creation', sa.INTEGER(), autoincrement=False, nullable=True, comment='Année de création de la pharmacie'))
    op.add_column('tenants', sa.Column('ip_restrictions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment="Liste d'IP autorisées"))
    op.add_column('tenants', sa.Column('langue', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('forme_juridique', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='SARL, SA, EI, etc.'))
    op.add_column('tenants', sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('ssl_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('compte_twitter', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('nombre_guichets', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('numero_ordre', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment="Numéro d'ordre du pharmacien"))
    op.add_column('tenants', sa.Column('numero_agrement', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment="Numéro d'agrément pharmaceutique"))
    op.add_column('tenants', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='mobile_money, bank_transfer, card, cash'))
    op.add_column('tenants', sa.Column('total_revenue', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('numero_national', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment="Numéro national d'entreprise"))
    op.add_column('tenants', sa.Column('telephone_mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('registre_commerce', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('specialite', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('nom_pharmacien', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('last_payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('page_facebook', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('mfa_required', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('max_api_calls_per_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('telephone_pharmacien', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('decimal_places', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('telephone_secondaire', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('prenom_pharmacien', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('total_sales', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('current_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('total_customers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('couleur_principale', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('superficie', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Superficie en m²'))
    op.add_column('tenants', sa.Column('adresse_ligne1', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('annual_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('couleur_secondaire', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('next_payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('total_inventory_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('api_secret', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('fax', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('max_customers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('custom_domain', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('api_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('email_proprietaire', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('total_products', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('cancelled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('devise_symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('horaires', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('max_storage_mb', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('nom_entreprise', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment="Nom légal de l'entreprise"))
    op.add_column('tenants', sa.Column('site_web', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('devise', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('telephone_proprietaire', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('format_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('last_backup_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('compte_instagram', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('last_sync_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('code_postal', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('format_heure', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('email_pharmacien', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('fuseau_horaire', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('numero_ifu', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Identification Fiscale Unique'))
    op.add_column('tenants', sa.Column('quartier', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('email_contact', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('billing_period', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='monthly, quarterly, annual'))
    op.add_column('tenants', sa.Column('favicon_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('prenom_proprietaire', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('slogan', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tenants_updated_by_fkey'), 'tenants', 'users', ['updated_by'], ['id'])
    op.drop_index('ix_tenants_plan', table_name='tenants')
    op.create_unique_constraint(op.f('tenants_registre_commerce_key'), 'tenants', ['registre_commerce'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tenants_numero_ifu_key'), 'tenants', ['numero_ifu'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tenants_numero_agrement_key'), 'tenants', ['numero_agrement'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tenants_custom_domain_key'), 'tenants', ['custom_domain'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tenants_api_key_key'), 'tenants', ['api_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tenants_telephone_principal'), 'tenants', ['telephone_principal'], unique=False)
    op.create_index(op.f('ix_tenants_nom_proprietaire'), 'tenants', ['nom_proprietaire'], unique=False)
    op.create_index(op.f('ix_tenants_nom_pharmacie'), 'tenants', ['nom_pharmacie'], unique=False)
    op.create_index(op.f('ix_tenants_current_plan'), 'tenants', ['current_plan'], unique=False)
    op.create_index(op.f('idx_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('idx_tenants_geo'), 'tenants', ['pays', 'province', 'ville'], unique=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tenants', 'current_plan',
               existing_type=sa.VARCHAR(length=50),
               comment="Plan d'abonnement actuel (starter, professional, enterprise)",
               existing_nullable=True)
    op.alter_column('tenants', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tenants', 'nombre_employes',
               existing_type=sa.INTEGER(),
               comment='Nombre d’employés de la pharmacie',
               existing_nullable=True)
    op.alter_column('tenants', 'type_pharmacie',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tenants', 'pays',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('tenants', 'email_admin',
               existing_type=sa.VARCHAR(length=150),
               comment="Email principal de l'administrateur",
               existing_nullable=False)
    op.alter_column('tenants', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment='Slug pour URLs personnalisées',
               existing_nullable=True)
    op.alter_column('tenants', 'tenant_code',
               existing_type=sa.VARCHAR(length=20),
               comment='Code unique de la pharmacie (ex: PHARMA-001)',
               existing_nullable=False)
    # ### end Alembic commands ###
