"""add_role_column_to_users

Revision ID: f52b042111b7
Revises: 46fa97b4e921
Create Date: 2026-03-21 10:31:31.601598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52b042111b7'
down_revision: Union[str, Sequence[str], None] = '46fa97b4e921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_inventory_items_product', 'inventory_items', ['tenant_id', 'product_id'], unique=False)
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.drop_index('ix_inventory_items_product', table_name='inventory_items')
    # ### end Alembic commands ###
