"""nouvelle_trash_and_history

Revision ID: f549dda78313
Revises: 5b1976b5f026
Create Date: 2026-04-01 23:42:05.114604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f549dda78313'
down_revision: Union[str, Sequence[str], None] = '5b1976b5f026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='create, update, delete, restore, view, export, login, logout, etc.'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='product, sale, user, client, supplier, stock, etc.'),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('entity_reference', sa.String(length=100), nullable=True, comment="Référence lisible de l'entité"),
    sa.Column('entity_name', sa.String(length=255), nullable=True, comment="Nom de l'entité"),
    sa.Column('action_description', sa.Text(), nullable=True, comment="Description textuelle de l'action"),
    sa.Column('old_data', sa.JSON(), nullable=True, comment='Données avant modification'),
    sa.Column('new_data', sa.JSON(), nullable=True, comment='Données après modification'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='success, error, warning, info'),
    sa.Column('error_message', sa.Text(), nullable=True, comment="Message d'erreur si l'action a échoué"),
    sa.Column('user_metadata', sa.JSON(), nullable=True, comment='Métadonnées additionnelles'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_history_created_at', 'user_history', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_user_history_entity', 'user_history', ['tenant_id', 'module', 'entity_id'], unique=False)
    op.create_index('idx_user_history_session', 'user_history', ['session_id'], unique=False)
    op.create_index('idx_user_history_tenant_action', 'user_history', ['tenant_id', 'action_type'], unique=False)
    op.create_index('idx_user_history_tenant_module', 'user_history', ['tenant_id', 'module'], unique=False)
    op.create_index('idx_user_history_tenant_user', 'user_history', ['tenant_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_user_history_action_type'), 'user_history', ['action_type'], unique=False)
    op.create_index(op.f('ix_user_history_created_at'), 'user_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_history_entity_id'), 'user_history', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_history_module'), 'user_history', ['module'], unique=False)
    op.create_index(op.f('ix_user_history_session_id'), 'user_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_history_tenant_id'), 'user_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_history_user_id'), 'user_history', ['user_id'], unique=False)
    op.create_table('trash_bin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pharmacy_id', sa.UUID(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False, comment='product, sale, user, client, supplier, stock, etc.'),
    sa.Column('original_id', sa.UUID(), nullable=False),
    sa.Column('original_reference', sa.String(length=100), nullable=True, comment='Référence originale'),
    sa.Column('original_name', sa.String(length=255), nullable=True, comment='Nom original'),
    sa.Column('data', sa.JSON(), nullable=False, comment="Données complètes de l'élément au moment de la suppression"),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('deleted_by_name', sa.String(length=100), nullable=True),
    sa.Column('deleted_by_email', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('deletion_reason', sa.Text(), nullable=True, comment='Raison de la suppression'),
    sa.Column('restored_at', sa.DateTime(), nullable=True),
    sa.Column('restored_by_id', sa.UUID(), nullable=True),
    sa.Column('restored_by_name', sa.String(length=100), nullable=True),
    sa.Column('auto_delete_at', sa.DateTime(), nullable=True, comment='Date de suppression automatique définitive'),
    sa.Column('is_restored', sa.Boolean(), nullable=False),
    sa.Column('trash_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restored_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trash_bin_auto_delete', 'trash_bin', ['auto_delete_at'], unique=False)
    op.create_index('idx_trash_bin_deleted_at', 'trash_bin', ['tenant_id', 'deleted_at'], unique=False)
    op.create_index('idx_trash_bin_deleted_by', 'trash_bin', ['deleted_by_id'], unique=False)
    op.create_index('idx_trash_bin_original', 'trash_bin', ['tenant_id', 'item_type', 'original_id'], unique=False)
    op.create_index('idx_trash_bin_pharmacy', 'trash_bin', ['pharmacy_id', 'item_type'], unique=False)
    op.create_index('idx_trash_bin_restored', 'trash_bin', ['tenant_id', 'is_restored'], unique=False)
    op.create_index('idx_trash_bin_tenant_type', 'trash_bin', ['tenant_id', 'item_type'], unique=False)
    op.create_index(op.f('ix_trash_bin_deleted_at'), 'trash_bin', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_trash_bin_deleted_by_id'), 'trash_bin', ['deleted_by_id'], unique=False)
    op.create_index(op.f('ix_trash_bin_is_restored'), 'trash_bin', ['is_restored'], unique=False)
    op.create_index(op.f('ix_trash_bin_item_type'), 'trash_bin', ['item_type'], unique=False)
    op.create_index(op.f('ix_trash_bin_original_id'), 'trash_bin', ['original_id'], unique=False)
    op.create_index(op.f('ix_trash_bin_pharmacy_id'), 'trash_bin', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_trash_bin_tenant_id'), 'trash_bin', ['tenant_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_trash_bin_tenant_id'), table_name='trash_bin')
    op.drop_index(op.f('ix_trash_bin_pharmacy_id'), table_name='trash_bin')
    op.drop_index(op.f('ix_trash_bin_original_id'), table_name='trash_bin')
    op.drop_index(op.f('ix_trash_bin_item_type'), table_name='trash_bin')
    op.drop_index(op.f('ix_trash_bin_is_restored'), table_name='trash_bin')
    op.drop_index(op.f('ix_trash_bin_deleted_by_id'), table_name='trash_bin')
    op.drop_index(op.f('ix_trash_bin_deleted_at'), table_name='trash_bin')
    op.drop_index('idx_trash_bin_tenant_type', table_name='trash_bin')
    op.drop_index('idx_trash_bin_restored', table_name='trash_bin')
    op.drop_index('idx_trash_bin_pharmacy', table_name='trash_bin')
    op.drop_index('idx_trash_bin_original', table_name='trash_bin')
    op.drop_index('idx_trash_bin_deleted_by', table_name='trash_bin')
    op.drop_index('idx_trash_bin_deleted_at', table_name='trash_bin')
    op.drop_index('idx_trash_bin_auto_delete', table_name='trash_bin')
    op.drop_table('trash_bin')
    op.drop_index(op.f('ix_user_history_user_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_tenant_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_session_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_module'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_entity_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_created_at'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_action_type'), table_name='user_history')
    op.drop_index('idx_user_history_tenant_user', table_name='user_history')
    op.drop_index('idx_user_history_tenant_module', table_name='user_history')
    op.drop_index('idx_user_history_tenant_action', table_name='user_history')
    op.drop_index('idx_user_history_session', table_name='user_history')
    op.drop_index('idx_user_history_entity', table_name='user_history')
    op.drop_index('idx_user_history_created_at', table_name='user_history')
    op.drop_table('user_history')
    # ### end Alembic commands ###
